src/AppBundle/Resources/translations/messages.fr.yml
passer commander > passer commande
=> Fixed typo

.gitignore, .travis.yml, README.md, app/AppKernel.php, app/config/config.yml, app/config/config_prod.yml, composer.json, composer.lock, config/deploy.rb, docker-compose.yml, features/bootstrap/FeatureContext.php, features/restaurants.feature, js/api/ConfigLoader.js, js/api/order/tracking.js, js/api/tracking/index.html, js/api/tracking/index.js, package.json, pm2.config.js, var/SymfonyRequirements.php, web/config.php, webpack.config.js
Seems to work ok
manifest.json will be used only in production : 
- `NODE_ENV` should be set to `production`
- `app/config/config_prod.yml` is used 
Fix #11
=> Add manifest.json file generation

app/DoctrineMigrations/Version20170921194951.php, assets/css/styles.scss, docker-compose.yml, features/bootstrap/FeatureContext.php, js/app/Cart.jsx, js/app/CartItem.jsx, js/app/cart/index.jsx, src/AppBundle/Command/Resources/menu.yml, src/AppBundle/Controller/OrderController.php, src/AppBundle/Controller/RestaurantController.php, src/AppBundle/Entity/Base/BaseAddress.php, src/AppBundle/Entity/Menu/MenuItem.php, src/AppBundle/Entity/Menu/MenuItemModifier.php, src/AppBundle/Entity/MenuItem.php, src/AppBundle/Entity/Order.php, src/AppBundle/Entity/OrderItem.php, src/AppBundle/Entity/OrderItemModifier.php, src/AppBundle/Faker/RestaurantProvider.php, src/AppBundle/Resources/views/Order/index.html.twig, src/AppBundle/Resources/views/Restaurant/index.html.twig, src/AppBundle/Serializer/MenuItemNormalizer.php, src/AppBundle/Utils/Cart.php, src/AppBundle/Utils/CartItem.php, tests/AppBundle/BaseTest.php, tests/AppBundle/Entity/OrderTest.php, tests/AppBundle/Utils/CartTest.php
Draft here: https://wireframe.cc/EwlU4S
=> Proposal and implementation for modifiers

app/AppKernel.php, app/config/config_prod.yml, app/config/parameters.yml.dist, app/config/parameters.yml.travis, composer.json, composer.lock
=> feat: add sentry support

assets/css/styles.scss, src/AppBundle/Resources/views/Restaurant/index.html.twig
I was not able to test with real data as the description field seems to be currently always null and I don't know how to populate it.
=> add menu items descriptions on the restaurants page.

app/DoctrineMigrations/Version20171122111003.php, assets/css/utils.scss, features/bootstrap/FeatureContext.php, features/fixtures/ORM/restaurants.yml, features/orders.feature, features/restaurants.feature, js/api/Db.js, js/app/cart/Cart.jsx, js/app/cart/index.jsx, js/tests/utils.js, src/AppBundle/Action/Order/Create.php, src/AppBundle/Command/InitDemoCommand.php, src/AppBundle/Controller/AdminController.php, src/AppBundle/Controller/OrderController.php, src/AppBundle/Controller/RestaurantTrait.php, src/AppBundle/Entity/Contract.php, src/AppBundle/Entity/Delivery.php, src/AppBundle/Entity/Order.php, src/AppBundle/Entity/Restaurant.php, src/AppBundle/Form/ApiRegistrationType.php, src/AppBundle/Form/ContractType.php, src/AppBundle/Form/RestaurantAdminType.php, src/AppBundle/Resources/translations/messages.en.yml, src/AppBundle/Resources/translations/messages.fr.yml, src/AppBundle/Resources/views/Restaurant/form.html.twig, src/AppBundle/Resources/views/Restaurant/index.html.twig, src/AppBundle/Serializer/RestaurantNormalizer.php, tests/AppBundle/Entity/OrderTest.php
They are editable by admin-only.
Contracts give us the following : 
- set deliveryPrice
- set basket max amount (and validate it)
=> Introduce contracts for restaurants

.gitignore, README.md, docker-compose-dev.yml, docker-sync.yml, docker/php/Dockerfile
Introducing [docker-sync](http://docker-sync.io/). It is kind of shitty becaus it's a hack on top of docker but the dev experience is aaaaamzazing with it (response time ~200ms)
@alexsegura can you test it on your machine?
=> feat: introduce docker-sync

app/AppKernel.php, app/DoctrineMigrations/Version20171206200442.php, app/config/config.yml, composer.json, composer.lock, docker/php/Dockerfile, docker/php/start.sh, js/app/restaurant/form.jsx, src/AppBundle/Controller/AdminController.php, src/AppBundle/Controller/AdminTrait.php, src/AppBundle/Controller/ProfileController.php, src/AppBundle/Controller/RestaurantTrait.php, src/AppBundle/Entity/Base/LocalBusiness.php, src/AppBundle/Entity/Contract.php, src/AppBundle/Entity/Restaurant.php, src/AppBundle/Form/RestaurantType.php, src/AppBundle/Resources/translations/messages.en.yml, src/AppBundle/Resources/translations/messages.fr.yml, src/AppBundle/Resources/translations/validators.en.yml, src/AppBundle/Resources/translations/validators.fr.yml, src/AppBundle/Resources/views/Admin/orders.html.twig, src/AppBundle/Resources/views/Order/invoice.html.twig, src/AppBundle/Resources/views/Profile/orders.html.twig, src/AppBundle/Resources/views/Restaurant/form.html.twig, src/AppBundle/Resources/views/_partials/Order/list.html.twig, src/AppBundle/Validator/Constraints/IsActivableRestaurant.php, src/AppBundle/Validator/Constraints/IsActivableRestaurantValidator.php, tests/AppBundle/Entity/RestaurantTest.php
Damn simple introduction of PDF invoices based on calculated amounts with taxes. 
Can you test the PDF rendering @Atala ? 
You need to rebuild the PHP container `docker-compose build php`
=> Introduce PDF invoices

Makefile, app/AppKernel.php, app/Resources/FOSUserBundle/views/Registration/email.txt.twig, app/config/config.yml, app/config/config_dev.yml, app/config/config_prod.yml, app/config/parameters.yml.dist, app/config/services.yml, assets/css/vars.scss, composer.json, composer.lock, docker-compose.yml, src/AppBundle/Command/PreviewEmailLayout.php, src/AppBundle/Entity/ApiUser.php, src/AppBundle/Entity/Listener/OrderListener.php, src/AppBundle/Form/DeliveryServiceType.php, src/AppBundle/Resources/translations/messages.en.yml, src/AppBundle/Resources/translations/messages.fr.yml, src/AppBundle/Resources/views/Emails/layout.html.twig, src/AppBundle/Resources/views/Emails/orderAccepted.html.twig, src/AppBundle/Resources/views/Emails/orderCancelled.html.twig, src/AppBundle/Resources/views/Emails/orderConfirmation.html.twig, src/AppBundle/Service/MailLoggerService.php, src/AppBundle/Service/MailjetTransport.php
Tested, works ok by me.
How to test or deploy?
Update `parameters.yml` : 
```
mailer_transport: mailjet # change
mailjet.api_key: public_key # insert
mailjet.secret_key: secret_key # insert
```
=> Transactional emails + Mailjet Support

.editorconfig, app/DoctrineMigrations/Version20171212151113.php, assets/css/styles.scss, assets/css/vars.scss, docker-sync.yml, js/app/cart/index.jsx, js/app/restaurant/OrderDetails.jsx, js/app/restaurant/OrderList.jsx, js/app/restaurant/parseOpeningHours.jsx, js/app/restaurant/planning.jsx, package-lock.json, package.json, src/AppBundle/Controller/AdminController.php, src/AppBundle/Controller/ProfileController.php, src/AppBundle/Controller/RestaurantTrait.php, src/AppBundle/Entity/ClosingRule.php, src/AppBundle/Entity/Restaurant.php, src/AppBundle/Form/ClosingRuleType.php, src/AppBundle/Form/MenuType/MenuSectionType.php, src/AppBundle/Form/MenuType/ModifierType.php, src/AppBundle/Resources/translations/messages.en.yml, src/AppBundle/Resources/translations/messages.fr.yml, src/AppBundle/Resources/views/Restaurant/form.html.twig, src/AppBundle/Resources/views/Restaurant/index.html.twig, src/AppBundle/Resources/views/Restaurant/planning.html.twig, tests/AppBundle/Entity/RestaurantTest.php, webpack.config.js
=> feat: add closing rules for restaurant and planning view in admin

app/AppKernel.php, app/config/services.yml, assets/css/styles.scss, composer.json, composer.lock, src/AppBundle/Controller/AdminController.php, src/AppBundle/Controller/HelpController.php, src/AppBundle/Form/UpdateProfileType.php, src/AppBundle/Resources/translations/messages.en.yml, src/AppBundle/Resources/translations/messages.fr.yml, src/AppBundle/Resources/views/Form/user.html.twig, src/AppBundle/Resources/views/Help/index.html.twig, src/AppBundle/Resources/views/Help/templates/admin/roles/index.en.md, src/AppBundle/Resources/views/Help/templates/admin/roles/index.fr.md, src/AppBundle/Resources/views/Help/templates/index.en.md, src/AppBundle/Resources/views/Help/templates/index.fr.md, src/AppBundle/Resources/views/base.html.twig
Admin can add/remove roles when modifying a user. 
Also, this pull request introduces help in Markdown 😉
=>  Allow editing user roles by admin.

app/DoctrineMigrations/Version20171228153019.php, app/config/config.yml, app/config/services.yml, features/bootstrap/FeatureContext.php, js/app/order/payment.js, src/AppBundle/Controller/OrderController.php, src/AppBundle/Controller/RestaurantController.php, src/AppBundle/Controller/StripeController.php, src/AppBundle/Entity/Cart/Cart.php, src/AppBundle/Entity/Cart/CartItem.php, src/AppBundle/Entity/Order.php, src/AppBundle/Resources/views/Order/payment.html.twig, src/AppBundle/Resources/views/Restaurant/index.html.twig, src/AppBundle/Resources/views/base.html.twig, src/AppBundle/Service/CartProviderService.php, tests/AppBundle/Entity/OrderTest.php, tests/AppBundle/Service/OrderManagerTest.php, tests/AppBundle/Utils/CartTest.php
Positive side-effect : a new address is created with each cart so we now have a unique delivery address per order :)
=> Save the cart in DB, not in session

app/DoctrineMigrations/Version20180409151356.php, src/AppBundle/Controller/Utils/DeliveryTrait.php, src/AppBundle/Form/PricingRuleType.php, src/AppBundle/Resources/translations/messages.en.yml, src/AppBundle/Resources/translations/messages.es.yml, src/AppBundle/Resources/translations/messages.fr.yml, src/AppBundle/Resources/views/Form/pricingRuleSet.html.twig
=> feat: use cents for pricing rules

app/DoctrineMigrations/Version20180416150733.php, app/config/state_machine.yml, src/AppBundle/Controller/Utils/OrderTrait.php, src/AppBundle/Entity/StripeTransfer.php, src/AppBundle/Entity/Sylius/Order.php, src/AppBundle/EventSubscriber/OrderSubscriber.php, src/AppBundle/Resources/config/doctrine/StripeTransfer.orm.yml, src/AppBundle/Service/OrderManager.php, src/AppBundle/Sylius/Order/OrderTransitions.php, src/AppBundle/Sylius/StripeTransfer/StripeTransferTransitions.php
=> Create Stripe transfers

assets/css/dashboard.scss, js/app/dashboard/components/Task.js, js/app/dashboard/components/TaskList.js, js/app/dashboard/components/TaskLists.js, package-lock.json, package.json
Proposition for changing the collapsable behavior for a scrollable one in the dashboard.
Pro : it's way easier to re-position tasks in a given task list
Cons : maybe too much scrollable things in this area
Fix #304 
I guess we should test it with real users
@alexsegura any thoughts?
=> Scrollable dashboard

app/DoctrineMigrations/Version20180516124244.php, features/bootstrap/FeatureContext.php, features/restaurants.feature, src/AppBundle/Controller/Utils/RestaurantTrait.php, src/AppBundle/Entity/Restaurant.php, src/AppBundle/Resources/config/doctrine/Restaurant.orm.yml, src/AppBundle/Resources/config/routing/admin.yml, src/AppBundle/Resources/config/routing/profile.yml, src/AppBundle/Resources/translations/messages.en.yml, src/AppBundle/Resources/translations/messages.es.yml, src/AppBundle/Resources/translations/messages.fr.yml, src/AppBundle/Resources/views/Restaurant/form.html.twig, src/AppBundle/Resources/views/Restaurant/menuTaxons.html.twig, src/AppBundle/Resources/views/_partials/Restaurant/list.html.twig, src/AppBundle/Serializer/JsonLd/RestaurantMenuNormalizer.php, src/AppBundle/Serializer/RestaurantNormalizer.php
It is now possible to create new menu, and change the menu which will be displayed on the frontend.
=> Allow switching between menus.

src/AppBundle/Resources/translations/messages.es.yml
Currently translated at 99.7% (390 of 391 strings)
Translation: CoopCycle/CoopCycle Web Messages
Translate-URL: http://translate.coopcycle.org/projects/coopcycle/coopcycle-web-messages/es/
=> Translated using Weblate (Spanish)

src/AppBundle/Resources/translations/messages.fr.yml
Currently translated at 100.0% (391 of 391 strings)
Translation: CoopCycle/CoopCycle Web
Translate-URL: http://translate.coopcycle.org/projects/coopcycle/coopcycle-web/fr/
=> Translated using Weblate (French)

app/DoctrineMigrations/Version20180615124802.php, src/AppBundle/Controller/RestaurantController.php, src/AppBundle/Entity/Sylius/ProductOption.php, src/AppBundle/Form/ProductOptionType.php, src/AppBundle/Resources/config/doctrine/Sylius.ProductOption.orm.yml, src/AppBundle/Resources/translations/messages.en.yml, src/AppBundle/Resources/translations/messages.es.yml, src/AppBundle/Resources/translations/messages.fr.yml, src/AppBundle/Resources/views/Form/productOption.html.twig, src/AppBundle/Resources/views/Restaurant/index.html.twig, src/AppBundle/Resources/views/Restaurant/productOption.html.twig, src/AppBundle/Sylius/Product/LazyProductVariantResolver.php, src/AppBundle/Sylius/Product/ProductOptionInterface.php, tests/AppBundle/Sylius/Product/LazyProductVariantResolverTest.php
=> Introduce additional product options

app/config/security.yml, app/config/services.yml, features/bootstrap/FeatureContext.php, features/foodtech.feature, features/restaurants.feature, src/AppBundle/Action/Restaurant/Close.php, src/AppBundle/Entity/ClosingRule.php, src/AppBundle/Entity/Restaurant.php, src/AppBundle/Serializer/ClosingRuleNormalizer.php, src/AppBundle/Serializer/RestaurantNormalizer.php, src/AppBundle/Utils/OpeningHoursSpecification.php, tests/AppBundle/Utils/OpeningHoursSpecificationTest.php
Also, it introduces [`OpeningHoursSpecification`](https://schema.org/OpeningHoursSpecification)
See #412
=> Allow managing opening hours through API

app/config/services.yml, assets/css/styles.scss, src/AppBundle/Command/SetupCommand.php, src/AppBundle/Entity/Sylius/Product.php, src/AppBundle/Enum/Allergen.php, src/AppBundle/Form/ProductType.php, src/AppBundle/Resources/translations/messages.en.yml, src/AppBundle/Resources/translations/messages.es.yml, src/AppBundle/Resources/translations/messages.fr.yml, src/AppBundle/Resources/views/Form/product.html.twig, src/AppBundle/Resources/views/Restaurant/index.html.twig, src/AppBundle/Resources/views/Restaurant/product.html.twig
This introduces allergens & restricted diets management for meals. 
⚠️ Please note this is just an introduction, to be able to link meals with allergens, and for the customer to see meals containing allergens. 
Features such as filtering will be discusses & managed later, if needed. 
On the product form, admins can check allergens & restricted diets for each product. 
Allergens are displayed with a warning icon. 
Restricted diets are displayed with a checkmark icon.
=> Allergens & restricted diets

app/DoctrineMigrations/Version20180922164908.php, js/app/dashboard/app.js, js/app/dashboard/components/Task.js, js/app/dashboard/components/TaskList.js, js/app/dashboard/store/reducers.js, src/AppBundle/Entity/Delivery.php, src/AppBundle/Entity/Task.php, src/AppBundle/Entity/TaskRepository.php, src/AppBundle/EventListener/TaskSubscriber.php, src/AppBundle/Resources/config/doctrine/Task.orm.yml, src/AppBundle/Serializer/TaskNormalizer.php
We should have done that since the beginning... It makes things WAY simpler to manage 🔁
Fixes #248
Fixes #448
Useful for 
- #212 
- coopcycle/coopcycle-app#64
=> Manage linked tasks a a doubly linked list

assets/css/styles.scss, js/app/cart/Cart.jsx, js/app/components/AddressPicker.jsx
This Pull Request triggers a modal to enter the address. 
The modal is triggered only when an address was not set previously. 
No modal is triggered for other use cases (for example, when the address is too far).
=> Address modal

README.md, docker-compose-portainer.yml, docker-compose.yml
Hello,
Hope this update would be better than the previous one to propose portainer enhancement 
https://github.com/coopcycle/coopcycle-web/issues/468
=> add portainer GUI

app/DoctrineMigrations/Version20181005192815.php, app/config/services.yml, src/AppBundle/Sylius/Order/OrderNumberAssigner.php
=> Use custom order number assigner.

docker/webpack/Dockerfile
by the way also adding bash & openssh
Fixes #493
=> fix npm git issue 493

app/config/services.yml, app/config/state_machine.yml, composer.lock, src/AppBundle/Controller/AdminController.php, src/AppBundle/Domain/Order/Command/Refund.php, src/AppBundle/Domain/Order/Handler/RefundHandler.php, src/AppBundle/Entity/StripePayment.php, src/AppBundle/Form/PaymentType.php, src/AppBundle/Resources/translations/messages.en.yml, src/AppBundle/Resources/translations/messages.es.yml, src/AppBundle/Resources/translations/messages.fr.yml, src/AppBundle/Resources/views/order/service.html.twig, src/AppBundle/Service/OrderManager.php, src/AppBundle/Service/StripeManager.php
=> Allow creating partial refunds

.travis.yml, behat.yml, composer.json, composer.lock, docker-compose.yml, docker/nginx_test/conf.d/default.conf, docker/nginx_test/conf.d/websocket_config, features/selenium.feature, web/app_test.php
This is a Zalenium + selenium-side-runner GUI tests proposal
=> Add zalenium test

.travis.yml, js/app/components/OpeningHours.jsx, js/app/i18n/locales/en.json, js/app/i18n/locales/es.json, js/app/i18n/locales/fr.json
Fix issue #435: "Missing internationalisation on new restaurant page"
=> Fix issue #435 Translate Open hours "table title" and "Add" buton

.gitattributes, .travis.yml, Makefile, README.md, composer.json, docker/nodejs/Dockerfile, docker/php/Dockerfile, docker/php/php.ini, docker/webpack/Dockerfile, web/app_dev.php
=> Make Docker work on Windows

app/DoctrineMigrations/Version20181212175050.php, src/AppBundle/Controller/Utils/StoreTrait.php, src/AppBundle/Entity/Store.php, src/AppBundle/Form/StoreType.php, src/AppBundle/Resources/config/doctrine/Store.orm.yml, src/AppBundle/Resources/translations/messages.en.yml, src/AppBundle/Resources/translations/messages.es.yml, src/AppBundle/Resources/translations/messages.fr.yml, src/AppBundle/Resources/views/store/form.html.twig
This is a way to revert the changes introduced in #504, until we find a better way.
=> Introduce configurable behavior for Store

.babelrc, .gitignore, .travis.yml, app/AppKernel.php, app/config/config.yml, composer.json, composer.lock, docker/webpack/start.sh, js/app/MapHelper.js, js/app/common.js, package-lock.json, package.json, src/AppBundle/Controller/AssetsController.php, src/AppBundle/Resources/views/_partials/app.js.twig, src/AppBundle/Resources/views/admin/dashboard_iframe.html.twig, src/AppBundle/Resources/views/admin/deliveries.html.twig, src/AppBundle/Resources/views/admin/foodtech_dashboard.html.twig, src/AppBundle/Resources/views/admin/pricing_rule_set.html.twig, src/AppBundle/Resources/views/admin/user_edit.html.twig, src/AppBundle/Resources/views/admin/zones.html.twig, src/AppBundle/Resources/views/base.html.twig, src/AppBundle/Resources/views/delivery/form.html.twig, src/AppBundle/Resources/views/restaurant/dashboard.html.twig, src/AppBundle/Resources/views/restaurant/form.html.twig, src/AppBundle/Resources/views/restaurant/map.html.twig, src/AppBundle/Resources/views/restaurant/menu_taxon.html.twig, src/AppBundle/Resources/views/user/tracking.html.twig, webpack.config.js
There is still a problem on Travis, but it definitely works.
=> Use latest Webpack Encore

app/config/parameters.yml.dist, app/config/routing.yml, app/config/services.yml, composer.json, composer.lock, features/bootstrap/FeatureContext.php, features/settings.feature, src/AppBundle/Controller/AdminController.php, src/AppBundle/Controller/AssetsController.php, src/AppBundle/Controller/IndexController.php, src/AppBundle/Controller/OrderController.php, src/AppBundle/Controller/ProfileController.php, src/AppBundle/Controller/PublicController.php, src/AppBundle/Controller/RestaurantController.php, src/AppBundle/Controller/SitemapController.php, src/AppBundle/Controller/StripeController.php, src/AppBundle/Controller/TagController.php, src/AppBundle/Controller/UserController.php, src/AppBundle/Controller/Utils/AdminDashboardTrait.php, src/AppBundle/Resources/config/routing/admin.yml, src/AppBundle/Resources/config/routing/profile.yml
=> Upgrade to Symfony 4

app/AppKernel.php, app/DoctrineMigrations/Version20190408202217.php, app/config/config.yml, app/config/services.yml, composer.json, composer.lock, src/AppBundle/Entity/Sylius/Order.php, src/AppBundle/Entity/Sylius/OrderRepository.php, src/AppBundle/Entity/Sylius/PromotionCoupon.php, src/AppBundle/Form/Sylius/Promotion/Action/PercentageDiscountConfigurationType.php, src/AppBundle/Resources/config/doctrine/Sylius.Order.orm.yml, src/AppBundle/Resources/config/doctrine/Sylius.PromotionCoupon.orm.yml, src/AppBundle/Sylius/Order/AdjustmentInterface.php, src/AppBundle/Sylius/Order/OrderInterface.php, src/AppBundle/Sylius/Promotion/Action/DeliveryPercentageDiscountPromotionActionCommand.php, src/AppBundle/Sylius/Promotion/Checker/Eligibility/PromotionCouponPerCustomerUsageLimitEligibilityChecker.php, src/AppBundle/Sylius/Promotion/PromotionCouponInterface.php
=> Introduce Sylius PromotionBundle

app/config/services.yml, app/config/services/twig.yml, src/AppBundle/Command/ApplyTaxesCommand.php, src/AppBundle/Entity/Sylius/Order.php, src/AppBundle/Resources/translations/messages.en.yml, src/AppBundle/Resources/translations/messages.es.yml, src/AppBundle/Resources/translations/messages.fr.yml, src/AppBundle/Resources/views/_partials/order/items.html.twig, src/AppBundle/Resources/views/order/foodtech.html.twig, src/AppBundle/Resources/views/order/index.html.twig, src/AppBundle/Resources/views/order/payment.html.twig, src/AppBundle/Sylius/Order/OrderInterface.php, src/AppBundle/Sylius/OrderProcessing/OrderTaxesProcessor.php, src/AppBundle/Twig/CoopCycleExtension.php, src/AppBundle/Twig/TaxRateRuntime.php
This Pull Request allows to split taxes totals per rate
=> Improve taxes management

.travis.yml, behat.yml, composer.json, composer.lock, docker-compose.yml, docker/php/Dockerfile, features/bootstrap/FeatureContext.php
Fixes #558 
- Install Chromium in Docker, enable symfony/panther.
- Deprecate Zalenium.
- Use dmore/behat-chrome-extension instead of behat/mink-selenium2-driver.
- Launch Chrome on Travis.
=> Use ChromeDriver instead of Selenium.

features/fixtures/ORM/dispatch.yml, src/AppBundle/Api/Filter/DateFilter.php, src/AppBundle/Api/Filter/TaskDateFilter.php, src/AppBundle/Entity/Task.php, src/AppBundle/Entity/TaskRepository.php
=> Allow tasks to properly span over several days

app/config/config_dev.yml, src/AppBundle/Controller/UserController.php, src/AppBundle/Resources/translations/messages.de.yml, src/AppBundle/Resources/translations/messages.en.yml, src/AppBundle/Resources/translations/messages.es.yml, src/AppBundle/Resources/translations/messages.fr.yml, templates/bundles/FOSUserBundle/Registration/check_email.html.twig
=> Resend email

assets/css/styles.scss, js/app/cart/components/Cart.js
=> fix too long list orders in panels

app/config/config.yml, app/config/services.yml, assets/css/styles.scss, features/pricing.feature, js/app/MapHelper.js, js/app/delivery/PricePreview.js, js/app/delivery/form.jsx, js/app/forms/delivery.js, package-lock.json, package.json, src/AppBundle/Action/Delivery/Pricing.php, src/AppBundle/Action/PricingRule/Evaluate.php, src/AppBundle/Api/DataTransformer/DeliveryInputDataTransformer.php, src/AppBundle/Api/DataTransformer/PricingRuleEvaluateInputDataTransformer.php, src/AppBundle/Api/Dto/DeliveryInput.php, src/AppBundle/Api/Dto/PricingRuleEvaluate.php, src/AppBundle/Api/Dto/YesNoOutput.php, src/AppBundle/Api/EventSubscriber/PricingSubscriber.php, src/AppBundle/Api/Resource/Pricing.php, src/AppBundle/Controller/Utils/DeliveryTrait.php, src/AppBundle/Controller/Utils/StoreTrait.php, src/AppBundle/Entity/Delivery/PricingRule.php, src/AppBundle/Resources/views/delivery/form.html.twig
➕Restore price calculation preview
➕Use API endpoint to calculate price
➕Allow debugging pricing rules
➕Improve JavaScript
**TODO**
=> Refactor delivery form

src/AppBundle/Resources/translations/messages.en.yml, src/AppBundle/Resources/translations/messages.fr.yml, src/AppBundle/Resources/views/profile/profile.html.twig, templates/bundles/FOSUserBundle/ChangePassword/change_password.html.twig, templates/bundles/FOSUserBundle/ChangePassword/change_password_content.html.twig
=> Style change password and profile page

app/config/services.yml, assets/css/styles.scss, composer.json, composer.lock, js/api/TokenVerifier.js, js/api/tracking/index.js, js/app/delivery/tracking.js, js/app/forms/delivery.js, src/AppBundle/Action/Me.php, src/AppBundle/Controller/PublicController.php, src/AppBundle/Entity/Delivery.php, src/AppBundle/Resources/translations/messages.en.yml, src/AppBundle/Resources/translations/messages.es.yml, src/AppBundle/Resources/translations/messages.fr.yml, src/AppBundle/Resources/views/delivery/form.html.twig, src/AppBundle/Resources/views/delivery/tracking.html.twig, src/AppBundle/Service/SocketIoManager.php, src/AppBundle/Twig/CoopCycleExtension.php, webpack.config.js
=> Introduce public tracking page

js/app/dashboard/app.js, js/app/dashboard/components/SearchPanel.js, js/app/dashboard/components/Task.js, js/app/dashboard/components/TaskList.js, js/app/dashboard/components/TaskLists.js, js/app/dashboard/components/UnassignedTasks.js, js/app/dashboard/dashboard.scss, js/app/dashboard/redux/actions.js, js/app/dashboard/redux/reducers.js, js/app/i18n/locales/en.json, js/app/i18n/locales/es.json, js/app/i18n/locales/fr.json
=> Add fuzzy search on dashboard.

src/AppBundle/Controller/AdminController.php, src/AppBundle/Resources/views/emails/order/_partials/items.mjml.twig
=> Add promotions lines in emails

src/AppBundle/Entity/ApiUser.php, src/AppBundle/Entity/Base/LocalBusiness.php, src/AppBundle/Entity/Base/PostalAddress.php, src/AppBundle/Form/AddressType.php, src/AppBundle/Form/Checkout/CheckoutAddressType.php, src/AppBundle/Form/DeliveryEmbedType.php, src/AppBundle/Form/RegistrationType.php
=> fix wrong phone number input

src/AppBundle/Controller/AdminController.php, src/AppBundle/Entity/Tag.php, src/AppBundle/Form/TagType.php, src/AppBundle/Resources/translations/messages.en.yml, src/AppBundle/Resources/translations/messages.fr.yml, src/AppBundle/Resources/views/admin/tags.html.twig, src/AppBundle/Service/TagManager.php
=> allow admin to remove tags

js/app/dashboard/components/LeafletMap.js, js/app/dashboard/components/MapProxy.js, js/app/dashboard/components/TaskModalContent.js
=> Allow connecting map markers

src/AppBundle/Controller/AdminController.php, src/AppBundle/Form/CreateUserType.php, src/AppBundle/Form/RegistrationType.php
=> Create user type form

js/app/cart/components/Time.js, js/app/i18n/locales/en.json, js/app/i18n/locales/es.json, js/app/i18n/locales/fr.json
=> Fix date delvery bad encoding

src/AppBundle/Form/TaskExportType.php
=> allow admin to export tags in csv tasks file

app/config/security.yml, app/config/services.yml, features/authentication.feature, features/bootstrap/FeatureContext.php, src/AppBundle/Action/ResettingReset.php, src/AppBundle/Action/ResettingSendEmail.php, src/AppBundle/Form/ApiResetPasswordType.php
related to https://github.com/coopcycle/coopcycle-app/issues/125
=> add `reset password` endpoints (send email and set new password)

js/app/components/OpeningHours.jsx, js/app/dashboard/components/FiltersModalContent.js, js/app/dashboard/components/Navbar.js, js/app/dashboard/components/TaskModalContent.js, js/app/restaurant/planning.jsx, js/app/widgets/DatePicker.js, js/app/widgets/DateTimePicker.js, js/app/widgets/MonthPicker.js
=> Locale provider deprecated fix

assets/css/styles.scss, js/app/foodtech/dashboard/components/Dashboard.js, js/app/foodtech/dashboard/redux/actions.js, js/app/i18n/locales/en.json, js/app/i18n/locales/fr.json, src/AppBundle/Resources/views/profile.html.twig
=> Allow toggling rush mode

src/AppBundle/Api/EventSubscriber/MaintenanceSubscriber.php, src/AppBundle/Api/EventSubscriber/PricingSubscriber.php, src/AppBundle/Api/EventSubscriber/RemotePushTokenSubscriber.php, src/AppBundle/Api/EventSubscriber/RestaurantSubscriber.php, src/AppBundle/Api/EventSubscriber/SoftDeletedSubscriber.php, src/AppBundle/EventListener/CarbonListener.php, src/AppBundle/EventListener/LocaleListener.php, src/AppBundle/EventListener/MaintenanceListener.php, src/AppBundle/EventListener/SeoListener.php, src/AppBundle/EventSubscriber/OrderSubscriber.php, src/AppBundle/EventSubscriber/ProfileSubscriber.php
fix #719
Kiss; I love open source.
=> Use new Symfony events.

app/DoctrineMigrations/Version20191004195153.php, app/config/services/validators.yml, features/bootstrap/FeatureContext.php, features/deliveries.feature, src/AppBundle/Api/EventSubscriber/DeliverySubscriber.php, src/AppBundle/Entity/Delivery.php, src/AppBundle/Entity/Store.php, src/AppBundle/Resources/config/doctrine/Store.orm.yml, src/AppBundle/Resources/translations/validators.en.yml, src/AppBundle/Resources/translations/validators.es.yml, src/AppBundle/Resources/translations/validators.fr.yml, src/AppBundle/Validator/Constraints/CheckDelivery.php, src/AppBundle/Validator/Constraints/CheckDeliveryValidator.php
=> Add new endpoint to check if a delivery is feasible

src/AppBundle/Controller/Utils/AdminDashboardTrait.php, src/AppBundle/Utils/TaskImageNamer.php, tests/AppBundle/Functional/TaskImageNamerTest.php
Followup to https://github.com/coopcycle/coopcycle-web/pull/749
=> Followup for #749: Refactor class instantiation

docker/php/Dockerfile, docker/php/start.sh
May fix some problems on Linux (#789)
=> Cleanup/simplify Dockerfile

app/config/services/serializer.yml, features/deliveries.feature, features/dispatch.feature, features/fixtures/ORM/tasks.yml, features/tasks.feature, js/app/dashboard/__tests__/utils.js, js/app/dashboard/components/Task.js, js/app/dashboard/redux/actions.js, js/app/dashboard/redux/reducers.js, js/app/dashboard/redux/utils.js, src/AppBundle/Entity/Delivery.php, src/AppBundle/Entity/Model/TaggableTrait.php, src/AppBundle/Entity/Tag.php, src/AppBundle/Entity/Task.php, src/AppBundle/Entity/Task/Group.php, src/AppBundle/Entity/TaskImage.php, src/AppBundle/Serializer/DeliveryNormalizer.php, src/AppBundle/Serializer/TaskImageNormalizer.php, src/AppBundle/Serializer/TaskNormalizer.php
=> Refactor normalization of deliveries & tasks

app/DoctrineMigrations/Version20191115181843.php, assets/css/styles.scss, js/app/restaurant/index.js, src/AppBundle/Controller/RestaurantController.php, src/AppBundle/Entity/Sylius/ProductOption.php, src/AppBundle/Entity/Sylius/ProductVariant.php, src/AppBundle/Entity/Sylius/ProductVariantOptionValue.php, src/AppBundle/Form/ProductOptionType.php, src/AppBundle/Form/Type/MinMaxType.php, src/AppBundle/Resources/config/doctrine/Sylius.ProductVariant.orm.yml, src/AppBundle/Resources/config/doctrine/Sylius.ProductVariantOptionValue.orm.yml, src/AppBundle/Resources/translations/messages.en.yml, src/AppBundle/Resources/translations/messages.fr.yml, src/AppBundle/Resources/translations/validators.fr.yml, src/AppBundle/Resources/views/form/product_option.html.twig, src/AppBundle/Resources/views/restaurant/index.html.twig, src/AppBundle/Resources/views/restaurant/product_option.html.twig, src/AppBundle/Resources/views/restaurant/product_options.html.twig, src/AppBundle/Sylius/OrderProcessing/OrderOptionsProcessor.php, src/AppBundle/Sylius/Product/LazyProductVariantResolver.php, src/AppBundle/Sylius/Product/ProductVariantInterface.php, tests/AppBundle/Controller/RestaurantControllerTest.php, tests/AppBundle/Entity/Sylius/ProductVariantTest.php, tests/AppBundle/Sylius/OrderProcessing/OrderOptionsFeeProcessorTest.php, tests/AppBundle/Sylius/OrderProcessing/OrderOptionsProcessorTest.php, tests/AppBundle/Sylius/Product/LazyProductVariantResolverTest.php
=>  Allow specifying a quantity per option value

app/DoctrineMigrations/Version20191212172101.php, app/config/services/forms.yml, assets/css/styles.scss, js/app/product/form.js, phpstan.neon, src/AppBundle/Entity/Sylius/Product.php, src/AppBundle/Entity/Sylius/ProductOptions.php, src/AppBundle/Form/ProductOptionWithPositionType.php, src/AppBundle/Form/ProductType.php, src/AppBundle/Resources/config/doctrine/Sylius.Product.orm.yml, src/AppBundle/Resources/config/doctrine/Sylius.ProductOptions.orm.yml, src/AppBundle/Resources/views/restaurant/index.html.twig, src/AppBundle/Resources/views/restaurant/product.html.twig, src/AppBundle/Twig/CoopCycleExtension.php
=> Allow sorting product options

app/config/config.yml, app/config/services.yml, src/AppBundle/Resources/views/_partials/order/restaurant_details.html.twig, src/AppBundle/Resources/views/_partials/restaurant/list_thumbnail.html.twig, src/AppBundle/Resources/views/_partials/restaurant/menu_item_inner.html.twig, src/AppBundle/Resources/views/form/restaurant.html.twig, src/AppBundle/Resources/views/form/store.html.twig, src/AppBundle/Resources/views/restaurant/form.html.twig, src/AppBundle/Resources/views/restaurant/index.html.twig, src/AppBundle/Resources/views/restaurant/product.html.twig, src/AppBundle/Twig/AppearanceRuntime.php, src/AppBundle/Twig/AssetsRuntime.php, src/AppBundle/Twig/CoopCycleExtension.php
=> Store images in S3 Object Storage

app/DoctrineMigrations/Version20191113125855.php, app/config/config.yml, app/config/services.yml, app/config/state_machine.yml, src/AppBundle/Domain/Order/Handler/CheckoutHandler.php, src/AppBundle/Entity/Sylius/Payment.php, src/AppBundle/Form/StripePaymentType.php, src/AppBundle/Resources/config/doctrine/Sylius.Order.orm.xml, src/AppBundle/Resources/config/doctrine/Sylius.Order.orm.yml, src/AppBundle/Resources/config/doctrine/Sylius.Payment.orm.xml, src/AppBundle/Resources/config/doctrine/Sylius.Payment.orm.yml, src/AppBundle/Service/StripeManager.php, src/AppBundle/Sylius/OrderProcessing/OrderPaymentProcessor.php, src/AppBundle/Sylius/Payment/StripeTrait.php, tests/AppBundle/Domain/Order/Handler/CheckoutHandlerTest.php, tests/AppBundle/Domain/Order/Handler/CreatePaymentIntentHandlerTest.php, tests/AppBundle/Domain/Order/Reactor/UpdateStateTest.php, tests/AppBundle/Service/StripeManagerTest.php
=> Use Sylius standard payment

.circleci/config.yml, app/config/config.yml, app/config/config_prod.yml, app/config/services.yml, docker-compose.yml, docker/php_worker/Dockerfile, src/AppBundle/Doctrine/EventSubscriber/TaskSubscriber.php, src/AppBundle/Message/PushNotification.php, src/AppBundle/MessageHandler/PushNotificationHandler.php, tests/AppBundle/Doctrine/EventSubscriber/TaskSubscriberTest.php
=> Introduce async message processing

app/config/services.yml, phpstan.neon, src/AppBundle/Api/DataTransformer/DeliveryInputDataTransformer.php, src/AppBundle/Api/EventSubscriber/DeliverySubscriber.php, src/AppBundle/Api/EventSubscriber/PricingSubscriber.php, src/AppBundle/Command/BotCommand.php, src/AppBundle/Service/Routing/Fallback.php, src/AppBundle/Service/Routing/Osrm.php, src/AppBundle/Service/Routing/OsrmWithFallback.php, src/AppBundle/Service/RoutingInterface.php, src/AppBundle/Validator/Constraints/OrderValidator.php, tests/AppBundle/Service/Routing/FallbackTest.php, tests/AppBundle/Validator/OrderValidatorTest.php
=> Add fault-tolerant routing service

app/config/config.yml, app/config/services.yml, js/app/dashboard/app.js, js/app/dashboard/components/Navbar.js, js/app/dashboard/redux/actions.js, js/app/dashboard/redux/middlewares.js, js/app/dashboard/redux/reducers.js, js/app/dashboard/redux/store.js, js/app/i18n/locales/en.json, js/app/i18n/locales/fr.json, package-lock.json, package.json, src/AppBundle/Controller/Utils/AdminDashboardTrait.php, src/AppBundle/Form/TaskUploadType.php, src/AppBundle/Message/ImportTasks.php, src/AppBundle/MessageHandler/ImportTasksHandler.php, src/AppBundle/Resources/views/admin/dashboard_iframe.html.twig, src/AppBundle/Utils/TaskSpreadsheetParser.php
=> Process imported file asynchronously

app/DoctrineMigrations/Version20200313092450.php, app/DoctrineMigrations/Version20200313093323.php, app/config/config_dev.yml, app/config/config_prod.yml, app/config/services.yml, js/app/cart/components/CartTotal.js, js/app/i18n/locales/en.json, js/app/i18n/locales/fr.json, src/AppBundle/Entity/Contract.php, src/AppBundle/Entity/Restaurant.php, src/AppBundle/Form/ContractType.php, src/AppBundle/Resources/config/doctrine/Contract.orm.xml, src/AppBundle/Resources/config/doctrine/Contract.orm.yml, src/AppBundle/Resources/translations/messages.en.yml, src/AppBundle/Resources/translations/messages.fr.yml, src/AppBundle/Resources/translations/validators.en.yml, src/AppBundle/Resources/translations/validators.fr.yml, src/AppBundle/Resources/views/restaurant/form.html.twig, src/AppBundle/Serializer/JsonLd/OrderNormalizer.php, src/AppBundle/Service/DeliveryManager.php, src/AppBundle/Service/Routing/Osrm.php, src/AppBundle/Sylius/OrderProcessing/OrderFeeProcessor.php, tests/AppBundle/Controller/RestaurantControllerTest.php, tests/AppBundle/Service/DeliveryManagerTest.php, tests/AppBundle/Sylius/OrderProcessing/OrderFeeProcessorTest.php, tests/AppBundle/Sylius/OrderProcessing/OrderOptionsFeeProcessorTest.php
=> Introduce variable fees

app/config/message_bus/order.yml, app/config/services.yml, app/config/services/forms.yml, js/app/widgets/StripePaymentForm.js, src/AppBundle/Controller/AdminController.php, src/AppBundle/Controller/OrderController.php, src/AppBundle/Controller/PaymentController.php, src/AppBundle/Domain/Order/Handler/CheckoutHandler.php, src/AppBundle/Domain/Order/Handler/RefuseOrderHandler.php, src/AppBundle/Domain/Order/Reactor/CapturePayment.php, src/AppBundle/Domain/Order/Reactor/UpdateState.php, src/AppBundle/Form/Checkout/ChargeStripeSourceType.php, src/AppBundle/Form/Checkout/CheckoutPaymentType.php, src/AppBundle/Form/LocalBusinessType.php, src/AppBundle/Form/OrderType.php, src/AppBundle/Form/RestaurantType.php, src/AppBundle/Resources/translations/messages.en.yml, src/AppBundle/Resources/translations/messages.fr.yml, src/AppBundle/Resources/views/order/_partials/buttons.html.twig, src/AppBundle/Resources/views/order/payment.html.twig, src/AppBundle/Resources/views/order/service.html.twig, src/AppBundle/Resources/views/order/wait_for_payment.html.twig, src/AppBundle/Resources/views/restaurant/form.html.twig, src/AppBundle/Service/StripeManager.php, tests/AppBundle/Domain/Order/Handler/CheckoutHandlerTest.php, tests/AppBundle/Domain/Order/Handler/RefuseOrderHandlerTest.php, tests/AppBundle/Domain/Order/Reactor/CapturePaymentTest.php, tests/AppBundle/Domain/Order/Reactor/UpdateStateTest.php, tests/AppBundle/Service/StripeManagerTest.php
=> Introduce Giropay for Germany

app/AppKernel.php, app/DoctrineMigrations/Version20200503133617.php, app/DoctrineMigrations/Version20200503164147.php, app/DoctrineMigrations/Version20200504055738.php, app/config/config.yml, composer.json, composer.lock, js/api/Db.js, js/tests/utils.js, src/AppBundle/Entity/ApiUser.php, src/AppBundle/Entity/Sylius/Customer.php, src/AppBundle/Resources/config/doctrine/ApiUser.orm.xml, src/AppBundle/Resources/config/doctrine/Sylius.Customer.orm.xml, src/AppBundle/Security/UserManager.php, src/AppBundle/Sylius/Customer/CustomerInterface.php
This pull request is here to prepare guest checkout. 
It introduces the `Customer` class from [Sylius](https://docs.sylius.com/en/latest/book/customers/customer_and_shopuser.html). 
Addresses have been moved to the `Customer` class. 
At the moment, registration is still required on the platform.
=> Introduce "customer" concept

webpack.config.js
I actually missed a spot for the pt-BR locales. Moment locales setup was pretty hidden hehe
=> Add moment pt-BR locale

js/app/i18n/locales/en.json
Small typo. Will be hunting for more.
=> Fixed typo in en.json

app/config/services.yml, src/Form/Type/PriceWithTaxType.php, src/Form/Type/ProductTaxCategoryChoiceType.php, src/Sylius/OrderProcessing/OrderTaxesProcessor.php, src/Sylius/Taxation/Resolver/TaxRateResolver.php, src/Sylius/Taxation/Resolver/TaxRateResolverInterface.php, tests/AppBundle/Sylius/OrderProcessing/OrderTaxesProcessorTest.php, tests/AppBundle/Sylius/Taxation/Resolver/TaxRateResolverTest.php
=> Allow resolving multiple tax rates

js/app/dashboard/components/LeafletMap.js, js/app/dashboard/components/MapProxy.js, js/app/dashboard/redux/actions.js, js/app/dashboard/redux/reducers.js, package-lock.json, package.json
=> Allow selecting an area on the map

js/app/dashboard/app.js, js/app/dashboard/components/TaskList.js, js/app/dashboard/components/UnassignedTasks.js, js/app/dashboard/redux/actions.js, js/app/dashboard/redux/reducers.js, package-lock.json, package.json
=> Allow drag'n'drop with multiple items

app/DoctrineMigrations/Version20200930122929.php, app/config/services.yml, features/bootstrap/FeatureContext.php, features/tasks.feature, src/Api/EventSubscriber/TaskOrganizationSubscriber.php, src/Entity/Task.php, src/Entity/Task/Group.php, src/Resources/config/doctrine/Task.orm.xml, src/Resources/translations/validators.en.yml, src/Validator/Constraints/TaskGroup.php, src/Validator/Constraints/TaskGroupValidator.php, tests/AppBundle/Entity/TaskTest.php
=> Allowing specifying a "ref" when importing tasks via API

app/config/services/forms.yml, js/app/delivery/embed-start.js, js/app/delivery/embed-start.scss, js/app/delivery/form.scss, js/app/delivery/packages.scss, js/app/forms/delivery.js, src/Controller/AdminController.php, src/Form/DeliveryEmbedType.php, src/Form/DeliveryType.php, src/Form/EmbedSettingsType.php, src/Resources/translations/messages.en.yml, templates/embed/delivery/start.html.twig, templates/form/delivery_embed.html.twig
=> Add time slot & package set to embed form settings

app/DoctrineMigrations/Version20201010061644.php, app/config/services/forms.yml, cypress/fixtures/stores.yml, cypress/integration/delivery.spec.js, js/app/widgets/admin.js, src/Controller/AdminController.php, src/Controller/EmbedController.php, src/Entity/DeliveryForm.php, src/Form/DeliveryEmbedType.php, src/Form/EmbedSettingsType.php, src/Resources/config/doctrine/DeliveryForm.orm.xml, templates/_partials/sdk.html.twig, templates/admin/embed.html.twig, templates/admin/forms.html.twig, templates/embed/delivery/breadcrumb.html.twig, templates/embed/delivery/start.html.twig, templates/embed/delivery/summary.html.twig, templates/restaurant/form/_partials/embed.html.twig
=> Introduce delivery forms, migrate from legacy

app/DoctrineMigrations/Version20201020102523.php, app/config/services.yml, src/Action/Restaurant/Deliveries.php, src/Action/Restaurant/Orders.php, src/Controller/AdminController.php, src/Controller/Utils/RestaurantTrait.php, src/Entity/Listener/OrderListener.php, src/Entity/Sylius/Order.php, src/Entity/Sylius/OrderRepository.php, src/Resources/config/doctrine/Sylius.Order.orm.xml, src/Sylius/Cart/RestaurantResolver.php, tests/AppBundle/Sylius/Cart/RestaurantResolverTest.php
=> Remove direct link between Order & Restaurant

app/config/services.yml, cypress/fixtures/checkout_hubs.yml, cypress/integration/checkout_hubs.js, src/Controller/RestaurantController.php, src/Entity/Listener/OrderListener.php, src/Service/StripeManager.php, src/Sylius/Cart/RestaurantCartContext.php, src/Sylius/Cart/RestaurantResolver.php, tests/AppBundle/Controller/RestaurantControllerTest.php, tests/AppBundle/Service/StripeManagerTest.php, tests/AppBundle/Sylius/Cart/RestaurantCartContextTest.php, tests/AppBundle/Sylius/Cart/RestaurantResolverTest.php
=> Introduce hubs of restaurants

app/DoctrineMigrations/Version20201027120051.php, js/app/i18n/locales/en.json, js/app/product/form.js, js/app/restaurant/components/ProductDetailsModal.js, js/app/restaurant/index.js, package-lock.json, package.json, src/Controller/Utils/RestaurantTrait.php, src/Entity/Sylius/Product.php, src/Entity/Sylius/ProductImage.php, src/EventListener/Upload/UploadListener.php, src/Resources/config/doctrine/Sylius.Product.orm.xml, src/Resources/config/doctrine/Sylius.ProductImage.orm.xml, src/Resources/config/routing/admin.yml, src/Resources/config/routing/profile.yml, templates/_partials/restaurant/menu_item_inner.html.twig, templates/restaurant/index.html.twig, templates/restaurant/product.html.twig
=> Allow multiple product images

.gitignore, js/app/coopcycle-frontend-js/dispatch/redux.js, js/app/coopcycle-frontend-js/index.js, js/app/dashboard/app.js, js/app/dashboard/components/ContextMenu.js, js/app/dashboard/components/CourierSelect.js, js/app/dashboard/components/ImportModalContent.js, js/app/dashboard/components/LeafletMap.js, js/app/dashboard/components/Navbar.js, js/app/dashboard/components/SearchPanel.js, js/app/dashboard/components/Task.js, js/app/dashboard/components/TaskList.js, js/app/dashboard/components/TaskLists.js, js/app/dashboard/components/TaskModalContent.js, js/app/dashboard/components/UnassignedTasks.js, js/app/dashboard/redux/actions.js, js/app/dashboard/redux/dispatchReducers.js, js/app/dashboard/redux/reducers.js, js/app/dashboard/redux/selectors.js, js/app/dashboard/redux/store.js, package-lock.json, package.json
refactoring only, and change the way how shared library is imported to make it easier to replace it with the local version during development
=> use CREATE_TASK_LIST_* reducers from the shared library

app/DoctrineMigrations/Version20201222143825.php, src/Entity/LocalBusiness/FulfillmentMethod.php, src/Form/DeliveryType.php, src/Form/Restaurant/FulfillmentMethodType.php, src/Form/Type/AsapChoiceLoader.php, src/OpeningHours/OpenCloseTrait.php, src/Resources/config/doctrine/LocalBusiness.FulfillmentMethod.orm.xml, src/Resources/translations/messages.en.yml, src/Resources/translations/messages.fr.yml, src/Utils/OrderTimeHelper.php, src/Utils/ShippingDateFilter.php, templates/form/restaurant.html.twig, tests/AppBundle/Form/Type/AsapChoiceLoaderTest.php, tests/AppBundle/OpeningHours/OpenCloseTraitTest.php, tests/AppBundle/Utils/ShippingDateFilterTest.php
Fixes #1887
Fixes #1846
Fixes #1796
Fixes #1388
Fixes #1007
Fixes #544
Fixes #531
=> Refactoring of opening hours

cypress/integration/checkout.spec.js, js/app/payment/stripe.js, src/Controller/EmbedController.php, src/Controller/PublicController.php, src/Controller/Utils/DeliveryTrait.php, src/Service/StripeManager.php, src/Sylius/Order/OrderFactory.php, templates/embed/delivery/summary.html.twig, templates/public/order.html.twig
Fixes #563 
This pull request needs rebase/more work since #707 has been merged
=> Use Stripe Payment Intents

js/app/dashboard/redux/middlewares.js, js/app/delivery/tracking.js, src/Controller/PublicController.php, templates/delivery/tracking.html.twig
=> Use Centrifugo instead of socket.io

Makefile, docker/osrm/Dockerfile, src/Service/Routing/Osrm.php, src/Service/Routing/OsrmWithFallback.php, src/Utils/RestaurantFilter.php
=> Bump OSRM to 5.22.0, use table service

src/Resources/translations/cuisines.fr.yml
=> Fix translation typo #2061

cypress/integration/address_search.spec.js, js/app/components/AddressAutosuggest.js, js/app/components/AddressAutosuggest/__tests__/cache.js, js/app/components/AddressAutosuggest/algolia.js, js/app/components/AddressAutosuggest/cache.js
=> Cache address suggestions & improve results

package-lock.json, package.json
=> bump ant.design to version 4.x

js/app/common.js, js/app/dashboard/components/FiltersModalContent.js, js/app/dashboard/components/SettingsModalContent.js, js/app/dashboard/components/TaskModalContent.js, js/app/widgets/DateTimePicker.js, package-lock.json, package.json
=> antd automatic fix

app/DoctrineMigrations/Version20210325091343.php, app/DoctrineMigrations/Version20210325114349.php, app/config/config.yml, app/config/message_bus/task.yml, app/config/security.yml, app/config/services.yml, features/fixtures/ORM/webhooks.yml, features/webhooks.feature, src/Action/Webhook/Create.php, src/Domain/Task/Reactor/TriggerWebhook.php, src/Entity/Webhook.php, src/Entity/WebhookExecution.php, src/Message/Webhook.php, src/MessageHandler/WebhookHandler.php, src/Resources/config/doctrine/Webhook.orm.xml, src/Resources/config/doctrine/WebhookExecution.orm.xml, src/Security/WebhookVoter.php, tests/AppBundle/Domain/Task/Reactor/TriggerWebhookTest.php, tests/AppBundle/MessageHandler/WebhookHandlerTest.php
=> Introduce Webhooks

js/app/delivery/__tests__/pricing-rule-parser.js, js/app/delivery/__tests__/with-order-items-total-range.json, js/app/delivery/pricing-rule-parser.js
=> Fix AST parsing

templates/restaurant/layout.html.twig
=> icon changed

js/app/dashboard/components/UnassignedTasks.js, js/app/dashboard/components/UnassignedTasksPopoverContent.js, js/app/dashboard/index.js, js/app/dashboard/redux/actions.js, js/app/dashboard/redux/middlewares.js, js/app/dashboard/redux/settingsReducers.js
=> Allow toggling recurrence rules

app/DoctrineMigrations/Version20210610172707.php, features/fixtures/ORM/dispatch.yml, features/tasks.feature, src/Entity/Task.php, src/Resources/config/doctrine/Task.orm.xml, tests/AppBundle/Entity/TaskTest.php
=> Introduce tasks metadata

src/Payment/Gateway.php, src/Sylius/Payment/EdenredTrait.php, templates/order/_partials/payment_form.html.twig, tests/AppBundle/Payment/GatewayTest.php, translations/messages.en.yml, translations/messages.fr.yml
Fixes #2519 
In the popup, a text explains what will happen.
=> Implement refunds with Edenred

js/app/dashboard/components/LeafletPopupContent.js, js/app/dashboard/components/OrderNumber.js, js/app/dashboard/components/Task.js, src/Domain/Order/Reactor/CreateTasks.php, tests/AppBundle/Domain/Order/Reactor/CreateTasksTest.php
=> Working on Reflect order number across the whole platform

src/Controller/IndexController.php, src/Controller/RestaurantController.php, src/Entity/LocalBusiness.php, src/Entity/LocalBusinessRepository.php, src/Twig/CoopCycleExtension.php, src/Twig/LocalBusinessRuntime.php, templates/index/index.html.twig, templates/restaurant/_partials/list_buttons.html.twig, templates/restaurant/pagination.html.twig, translations/messages.en.yml
Fixes #2385
See #2523
This changes the algorithm of the homepage, to show shops organized by business type
---
Also, it adds tabs for filtering on list page
=> Refactor homepage

app/config/services.yml, src/Entity/Sylius/Order.php, src/Sylius/Order/OrderInterface.php, src/Sylius/OrderProcessing/OrderDepositRefundProcessor.php, src/Sylius/OrderProcessing/OrderFeeProcessor.php, templates/_partials/order/items.html.twig, tests/AppBundle/Sylius/OrderProcessing/OrderFeeProcessorTest.php, translations/messages.en.yml, translations/messages.fr.yml
=> Collect a processing fee for LoopEat

app/config/services.yml, js/app/components/PricePerPackageEditor.js, js/app/delivery/__tests__/price-per-package-function.json, js/app/delivery/__tests__/price-per-package.json, js/app/delivery/__tests__/pricing-rule-parser.js, js/app/delivery/pricing-rule-parser.js, js/app/delivery/pricing-rules.js, js/app/i18n/locales/en.json, js/app/i18n/locales/fr.json, src/ExpressionLanguage/PricePerPackageExpressionLanguageProvider.php, tests/AppBundle/ExpressionLanguage/PricePerPackageExpressionLanguageProviderTest.php, tests/AppBundle/ExpressionLanguage/PriceRangeExpressionLanguageProviderTest.php
=> Add an editor for price per package

js/app/foodtech/dashboard/components/ModalContent.js, js/app/foodtech/dashboard/components/OrderItems.js, js/app/foodtech/dashboard/index.scss, js/app/foodtech/dashboard/redux/selectors.js, templates/emails/order/accepted.mjml.twig
Fixes #2438
Items are now grouped by vendor
Vendors see items from other vendors blurred
=> Improve hub orders

src/Form/TimeSlotType.php
=> Add more days to time slot interval property

app/config/services.yml, features/orders.feature, src/Action/Order/Pay.php, src/Action/Order/PaymentMethods.php, src/Api/Dto/PaymentMethodsOutput.php, src/Entity/Sylius/Order.php, tests/AppBundle/Action/Order/PayTest.php
Needed by coopcycle/coopcycle-app#1161
=> Allow listing payment methods & paying via cash with API

templates/order/summary.txt.twig
=> tipAmout added to template

src/Entity/Listener/DeliveryListener.php
=> Adding weight and packages info

js/app/delivery/form.scss, js/app/forms/delivery.js, src/Form/DeliveryType.php, src/Form/TaskType.php, templates/delivery/form.html.twig, templates/form/delivery.html.twig
=> Allow adding multiple dropoffs when creating a delivery

js/app/dashboard/components/ContextMenu.js, js/app/dashboard/components/CreateGroupModalContent.js, js/app/dashboard/components/Modals.js, js/app/dashboard/redux/actions.js, js/app/dashboard/redux/reducers.js, js/app/dashboard/redux/taskEntityReducers.js, js/app/i18n/locales/en.json
=> Allow creating task group.

app/DoctrineMigrations/Version20211202100837.php, app/config/security.yml, app/config/services.yml, app/config/services/serializer.yml, features/tasks.feature, src/Action/Task/BulkAsync.php, src/Api/EventSubscriber/TaskImportQueueSubscriber.php, src/Entity/Task/Group.php, src/Entity/Task/ImportQueue.php, src/Message/ImportTasks.php, src/MessageHandler/ImportTasksHandler.php, src/Resources/config/doctrine/Task.ImportQueue.orm.xml, src/Serializer/TaskImportQueueNormalizer.php
=> Add API endpoint to import tasks asynchronously.

app/config/security.yml, features/carts.feature, features/orders.feature, src/Action/Order/Assign.php, src/Controller/OrderController.php, src/Entity/Sylius/Order.php, tests/Behat/FeatureContext.php
=> Guest checkout from mobile app

templates/admin/users.html.twig
Added customer full name in users list
=> Customer name list

src/Resources/config/serialization.yml
Useful for displaying customer name in the application
=> Added customer full name to API

features/foodtech.feature, features/orders.feature, features/restaurants.feature, features/shops.feature, js/app/cart/components/CartButton.js, js/app/i18n/locales/en.json, js/app/i18n/locales/es.json, js/app/i18n/locales/fr.json, js/app/restaurant/index.scss, js/app/restaurant/list.scss, src/Serializer/RestaurantNormalizer.php, templates/_partials/restaurant/list_thumbnail.html.twig, templates/restaurant/index.html.twig, translations/messages.en.yml, translations/messages.es.yml, translations/messages.fr.yml
Changes in WEB and API to improve how we show and handle the different posibilites of a closed restaurant.
UI changes for WEB:
- **(1)** List of restaurants, when a restaurant is closed we show an icon, the label 'closed now' and the background has less opacity. In this case we have these restaurants:
- La isla oriental: opened
- La berenjena: closed but opens today later
- La silla caliente: closed but opens tomorrow
- La sarten que fuma: closed and opens another day that is not today or tomorrow
- La patata caliente: closed with a closing rule, not available
- **(2)** Restaurant page, when it's open the button label is "Order" because it's available to receive orders:
- **(3)** Restaurant page, when it's closed but opens today:
- **(4)** Restaurant page, when it's closed but opens …
=> Closed restaurants improvements

js/app/payment/mercadopago.js, templates/embed/delivery/summary.html.twig, templates/order/payment.html.twig
We are sending the public key of the market place owner and the test in production has failed. 
I guess because we have to send the public key of the restaurant instead.
=> set restaurant public key

app/config/services.yml, src/Api/DataProvider/RestaurantCollectionDataProvider.php, src/Controller/IndexController.php, src/Controller/RestaurantController.php, src/Controller/TimingController.php, src/Service/TimingRegistry.php, src/Utils/SortableRestaurantIterator.php
=> Refactor restaurant sort

app/DoctrineMigrations/Version20220125114839.php, app/config/config.yml, app/config/message_bus/order.yml, app/config/security.yml, features/authentication.feature, features/foodtech.feature, src/Controller/AdminController.php, src/Controller/Utils/RestaurantTrait.php, src/Domain/Order/Reactor/TriggerWebhook.php, src/Entity/ApiApp.php, src/Form/ApiAppType.php, src/MessageHandler/WebhookHandler.php, src/Resources/config/doctrine/ApiApp.orm.xml, src/Resources/config/routing/admin.yml, src/Security/OrderActionsVoter.php, src/Security/TokenStoreExtractor.php, templates/_partials/api_app/list.html.twig, templates/admin/api_apps.html.twig, templates/restaurant/api.html.twig, templates/restaurant/api_form.html.twig, tests/AppBundle/MessageHandler/WebhookHandlerTest.php, tests/Behat/FeatureContext.php
=> Trigger webhooks for new orders

app/config/config.yml, app/config/services.yml, composer.json, composer.lock
=> Allow snc/redis-bundle 4.x, upgrade session configuration

app/config/config.yml, app/config/services.yml, js/app/cart/redux/actions.js, src/Embed/Context.php, src/EventSubscriber/EmbedSubscriber.php, src/Routing/EmbedAwareRouter.php
=> Use custom router to transmit "embed" param to all routes

app/config/services/commands.yml, composer.json, composer.lock, js/app/dashboard/components/MapProxy.js, src/Command/RegenerateAvatarsCommand.php, src/Controller/UserController.php
Fixes #776
Fixes #1646
Fixes #1911
=> Use color hashing functions for avatars.

app/AppKernel.php, app/DoctrineMigrations/Version20220208172631.php, app/config/config.yml, app/config/routing.yml, composer.json, composer.lock, features/fixtures/ORM/webhooks.yml, src/Action/Me.php, src/Action/Webhook/Create.php, src/Api/EventSubscriber/SubresourceDenyAccessListener.php, src/Controller/AdminController.php, src/DependencyInjection/Security/Factory/TokenBearerFactory.php, src/Entity/ApiApp.php, src/Entity/Webhook.php, src/Form/ApiAppType.php, src/Resources/config/doctrine/ApiApp.orm.xml, src/Resources/config/doctrine/Webhook.orm.xml, src/Security/BearerTokenAuthenticator.php, src/Security/CartSessionAuthenticator.php, src/Security/DeliveriesVoter.php, src/Security/OrderActionsVoter.php, src/Security/TaskOperationsVoter.php, src/Security/TokenStoreExtractor.php, src/Security/WebhookVoter.php, tests/AppBundle/MessageHandler/WebhookHandlerTest.php, tests/Behat/FeatureContext.php
=> Use league/oauth2-server-bundle.

js/app/delivery/form.js, src/Controller/Utils/StoreTrait.php, src/Form/DeliveryType.php, src/Form/NewOrderType.php, templates/delivery/form.html.twig, translations/messages.en.yml, translations/messages.fr.yml
=> Allow defining a price for a delivery manually.

js/app/components/PriceRangeEditor.js, js/app/components/RulePickerLine.js, js/app/delivery/__tests__/pricing-rule-parser.js, js/app/delivery/__tests__/with-packages-total-volume-units-range.json, js/app/delivery/__tests__/with-packages-total-volume-units.json, js/app/delivery/pricing-rule-parser.js, js/app/i18n/locales/en.json, js/app/i18n/locales/fr.json, src/ExpressionLanguage/PackagesResolver.php, tests/AppBundle/ExpressionLanguage/PackagesResolverTest.php, tests/AppBundle/ExpressionLanguage/PriceRangeExpressionLanguageProviderTest.php
=> Add pricing rule based on total volume units of packages

app/config/security.yml, cube/Loopeat.js, js/app/metrics/loopeat.js, src/Controller/ProfileController.php, templates/profile.html.twig, templates/profile/loopeat.html.twig, webpack.config.js
=> Add page to view Loopeat metrics.

src/Controller/AdminController.php, src/Controller/DashboardController.php, src/Controller/Utils/StoreTrait.php, templates/store/list.html.twig
The DESC sorting by name is still not working. Line 58 of StoreTrait.php
=> Stores pagination

js/app/dashboard/components/TaskModalContent.js, js/app/dashboard/dashboard.scss, js/app/i18n/locales/en.json, js/app/i18n/locales/es.json
This is how it looks:
https://user-images.githubusercontent.com/4819244/154550753-72e9cbfa-c405-4f9d-861b-cc605892a3b3.mp4
=> Add packages and weight info to task modal on dashboard

js/app/components/RulePickerLine.js, js/app/delivery/__tests__/pricing-rule-parser.js, js/app/delivery/__tests__/with-time-range-length-dropoff.json, js/app/delivery/__tests__/with-time-range-length.json, js/app/delivery/pricing-rule-parser.js, js/app/i18n/locales/en.json, js/app/i18n/locales/fr.json, src/Entity/Delivery.php, src/ExpressionLanguage/PickupExpressionLanguageProvider.php, src/Validator/Constraints/PricingRuleValidator.php, tests/AppBundle/ExpressionLanguage/PickupExpressionLanguageProviderTest.php
=> Add pricing condition for task time range

templates/order/foodtech.html.twig, templates/order/index.html.twig, templates/restaurant/index.html.twig, templates/restaurant/list.html.twig
Closes #3205 
With this PR we are asking for optin consent on:
- shops list
- shop detail
- checkout
- checkout summary
=> ask for optin consents on more pages

app/config/services.yml, src/Command/SetupCommand.php, src/Resources/config/taxation.yml
=> Enable Chile

js/app/restaurant/list.js, src/Controller/RestaurantController.php, templates/_partials/restaurant/shops_list.html.twig
With this PR we using AJAX for make requests when filters are applied.
https://user-images.githubusercontent.com/4819244/164298702-36db2a24-47fc-4e03-bdd7-93172c4b7933.mp4
=> Use ajax for filtering

js/app/cart/components/AddressModal.js, js/app/cart/components/Cart.js, js/app/cart/redux/reducers.js, js/app/i18n/locales/en.json, js/app/i18n/locales/es.json, js/sdk/modal.css
Closes #3216 
@ERAMANrepartos  With this PR:
- Embed modal size is changed to cover more screen
- In Address modal if user is in a restaurant page the back button keeps the user in that page
https://user-images.githubusercontent.com/4819244/171259457-3b748777-e879-4653-bec0-1a74d68027ba.mp4
=> Improve embed restaurant modal

app/DoctrineMigrations/Version20220531133301.php, src/Controller/AdminController.php, src/Entity/Vehicle.php, src/Form/VehicleType.php, src/Resources/config/doctrine/Vehicle.orm.xml, templates/admin/vehicle.html.twig, templates/admin/vehicles.html.twig, templates/form/delivery.html.twig, templates/form/delivery_embed.html.twig, translations/messages.en.yml
=> Introduce vehicles

app/DoctrineMigrations/Version20220708080640.php, app/config/services.yml, features/delivery_quotes.feature, features/fixtures/ORM/sylius_products.yml, src/Action/Delivery/ConfirmQuote.php, src/Action/Delivery/Quote.php, src/Api/DataTransformer/DeliveryInputDataTransformer.php, src/Entity/DeliveryQuote.php, src/Resources/config/doctrine/DeliveryQuote.orm.xml, src/Security/DeliveryQuoteVoter.php
=> Implement quote system for deliveries

app/config/message_bus/order.yml, src/Domain/Order/Handler/CancelOrderHandler.php, tests/AppBundle/Domain/Order/Handler/CancelOrderHandlerTest.php
=> refund canceled orders when made with giropay

features/carts.feature, src/Api/DataTransformer/CartSessionInputDataTransformer.php, src/Api/Dto/CartSessionInput.php
=> Allow specifying a shipping address when creating cart session.

app/DoctrineMigrations/Version20220805151009.php, src/Entity/Package.php, src/Form/PackageType.php, src/Resources/config/doctrine/Package.orm.xml, src/Spreadsheet/DeliverySpreadsheetParser.php, src/Spreadsheet/ParsePackagesTrait.php, src/Spreadsheet/TaskSpreadsheetParser.php, tests/AppBundle/Spreadsheet/DeliverySpreadsheetParserTest.php, tests/AppBundle/Spreadsheet/TaskSpreadsheetParserTest.php
=> Allow importing packages via spreadsheets

features/woopit.feature, src/Action/Woopit/AddressTrait.php, src/Action/Woopit/CreateDeliveryTrait.php, src/Action/Woopit/PackagesTrait.php, src/Action/Woopit/UpdateDeliveryTrait.php, src/Domain/Task/Reactor/TriggerWebhook.php, src/Entity/Listener/DeliveryListener.php, src/MessageHandler/WoopitWebhookHandler.php, tests/AppBundle/MessageHandler/WoopitWebhookHandlerTest.php
=> Fixes for woopit

src/Entity/Task.php
Is used for billing fast deliveries
=> Added task creation date to API

app/config/security.yml, app/config/services.yml, features/dispatch.feature, features/fixtures/ORM/stores_with_orgs.yml, features/fixtures/ORM/tasks_with_orgs.yml, src/Api/DataProvider/TaskListCollectionDataProvider.php, src/Api/Filter/OrganizationFilter.php, src/Entity/Task.php, src/Entity/Task/Group.php, src/Entity/TaskList.php
This allows OAuth clients to retrieve task lists, with only the tasks associated to the authenticated token store.
=> Allow to retrieve task lists via OAuth

js/app/i18n/locales/en.json, js/app/i18n/locales/es.json, js/app/termsAndConditionsAndPrivacyPolicy/LegalTextModal.js, js/app/termsAndConditionsAndPrivacyPolicy/index.js, js/app/termsAndConditionsAndPrivacyPolicy/index.scss, templates/bundles/NucleosProfileBundle/Registration/register_content.html.twig, webpack.config.js
Closes #3376 
https://user-images.githubusercontent.com/4819244/187995001-4112342c-0893-483f-b3cd-32ea6af57464.mp4
=> New terms and privacy policy modal

app/config/security.yml, src/Action/Order/Tip.php, src/Entity/Sylius/Order.php
PUT `/api/orders/[id]/tip`
```
{
"tipAmount": 200
}
```
=> feat(tip): add api endpoint for tips

src/Controller/AdminController.php, src/Entity/Delivery/PricingRuleSet.php, templates/admin/pricing.html.twig, translations/messages.en.yml, translations/messages.es.yml
=> Allow duplicating a pricing rule

app/config/config.yml, app/config/security.yml, app/config/services.yml, features/search.feature, js/app/common.js, js/app/i18n/locales/en.json, js/app/i18n/locales/fr.json, js/app/search/navbar.js, js/app/search/navbar.scss, package-lock.json, package.json, src/Action/Search/ShopsProducts.php, src/Api/Resource/Search.php, templates/menu.html.twig
=> Allow searching for restaurants & products.

src/Controller/AdminController.php, src/Controller/DashboardController.php, src/Controller/Utils/StoreTrait.php
Closes #3534 
**Create orders when importing deliveries (as ADMIN user)**
https://user-images.githubusercontent.com/4819244/217561314-cbebe35f-6780-4faa-996e-2937125f6091.mp4
**Create orders when importing deliveries (as STORE user)**
https://user-images.githubusercontent.com/4819244/217561209-b6ab3476-39fe-4317-9bd1-61289d0bc8b1.mp4
=> Create orders when import deliveries for a store

app/DoctrineMigrations/Version20221130143018.php, js/app/components/SavedCreditCard.js, js/app/i18n/locales/en.json, js/app/i18n/locales/es.json, js/app/i18n/locales/fr.json, js/app/payment/stripe.js, js/app/widgets/StripePaymentForm.js, src/Controller/StripeController.php, src/Entity/User.php, src/Form/StripePaymentType.php, src/Payment/Gateway.php, src/Resources/config/doctrine/User.orm.xml, src/Service/StripeManager.php, src/Sylius/Payment/StripeTrait.php, templates/embed/delivery/summary.html.twig, templates/order/payment.html.twig, tests/AppBundle/Controller/StripeControllerTest.php, tests/AppBundle/Payment/GatewayTest.php, tests/AppBundle/Service/StripeManagerTest.php
#2207 
Users can save a credit card for future usages.
**Pay and save credit card**
https://user-images.githubusercontent.com/4819244/209701610-77a740c8-da75-4d18-bf6f-4a720b1551fe.mp4
**New order in a different restaurant and user can reuse credit card saved before**
https://user-images.githubusercontent.com/4819244/209701684-37a043ca-f9b4-45bc-8669-5b419251b2a2.mp4
**Pay with a new card and save it**
https://user-images.githubusercontent.com/4819244/209701795-d64db166-b83d-4ef0-8889-0db28414d0c9.mp4
**Pay with a new card and don't save it**
https://user-images.githubusercontent.com/4819244/209701850-4574568d-8764-455a-81e1-7e8e00d2d03b.mp4
=> Save and reuse cards

app/config/security.yml, docker-compose.yml, features/stripe_payment_methods.feature, src/Action/MyStripePaymentMethods.php, src/Action/Order/CloneStripePayment.php, src/Action/Order/CreateSetupIntentOrAttachPM.php, src/Action/Order/Pay.php, src/Api/Dto/StripePaymentMethodOutput.php, src/Api/Dto/StripePaymentMethodsOutput.php, src/Entity/Sylius/Order.php, src/Entity/User.php, src/Service/StripeManager.php, tests/AppBundle/Service/StripeManagerTest.php, tests/Behat/FeatureContext.php
New endpoints and functionality to support save and reuse credit cards in mobile app.
=> Save and reuse cards in app

app/DoctrineMigrations/Version20230321150513.php, app/config/message_bus/order.yml, app/config/services.yml, js/app/components/OrdersRateLimiter.js, js/app/i18n/locales/de.json, js/app/i18n/locales/en.json, js/app/i18n/locales/es.json, js/app/i18n/locales/fr.json, js/app/i18n/locales/it.json, js/app/restaurant/fulfillment-methods.js, src/Domain/Order/Reactor/OrdersRateLimitReactor.php, src/Entity/LocalBusiness.php, src/Form/Restaurant/FulfillmentMethodsTrait.php, src/Resources/config/doctrine/LocalBusiness.orm.xml, src/Utils/OrdersRateLimit.php, src/Utils/ShippingDateFilter.php, templates/form/restaurant.html.twig, templates/restaurant/form/_partials/fulfillment.html.twig, tests/AppBundle/Utils/OrdersRateLimitFunctionalTest.php, tests/AppBundle/Utils/OrdersRateLimitTest.php, tests/AppBundle/Utils/ShippingDateFilterTest.php, translations/messages.de.yml, translations/messages.en.yml, translations/messages.es.yml, translations/messages.fr.yml, translations/messages.it.yml
=> X orders per Y minutes

bin/demo
huh yeah don't ask, it just works
=> fix(script): add Typesense init in seeders

js/app/dashboard/components/Task.js, js/app/dashboard/components/TaskList.js, js/app/dashboard/components/Tour.js, js/app/dashboard/redux/actions.js, js/app/i18n/locales/en.json, js/shared/src/logistics/redux/__tests__/selectors.test.js, js/shared/src/logistics/redux/index.js, js/shared/src/logistics/redux/selectors.js
=> Show tours as folders on TaskLists

app/config/services/forms.yml, cube.js, cube/TaskFailedEvent.js, cube/TaskFinishedEvent.js, cube/TaskTagging.js, cube/TasksExportUnified.js, src/Form/TaskExportType.php
=> New tasks export using Cube

app/config/message_bus/task.yml, features/tasks.feature, src/Action/Task/BulkMarkAsDone.php, src/Domain/Task/Handler/MarkAsDoneHandler.php, translations/messages.en.yml, translations/messages.es.yml
- New behavior when there is an error trying to complete multiple tasks:
a. Successfully close all the tasks that can be closed
b. Attach an error message to each task that couldn't be closed
c. Return the list of successfully completed tasks and a map of failed tasks with their own error message.
=> improve mark tasks as done

app/config/services.yml
=> allow mercadopago for colombia

src/Form/HubType.php, src/Form/Restaurant/FulfillmentMethodsTrait.php
=> Do not add rate limiter for hubs form

app/DoctrineMigrations/Version20230531134316.php, features/carts.feature, features/fixtures/ORM/reusable_packaging.yml, js/app/product/form.js, src/Controller/Utils/RestaurantTrait.php, src/Entity/ReusablePackaging.php, src/Entity/ReusablePackagings.php, src/Entity/Sylius/Order.php, src/Entity/Sylius/Product.php, src/Form/ProductType.php, src/Form/ReusablePackagingChoiceLoader.php, src/Form/ReusablePackagingType.php, src/Resources/config/doctrine/ReusablePackaging.orm.xml, src/Resources/config/doctrine/ReusablePackagings.orm.xml, src/Resources/config/doctrine/Sylius.Product.orm.xml, src/Sylius/OrderProcessing/OrderDepositRefundProcessor.php, templates/form/product.html.twig, templates/restaurant/product.html.twig, tests/AppBundle/Sylius/OrderProcessing/OrderDepositRefundProcessorTest.php, tests/Behat/FeatureContext.php
Fixes #3577 
This is a prerequisite to implement IMPEC. 
It's now possible to setup **multiple** reusable packagings per product.
=> Introduce multiple reusable packagings per product.

js/app/cart/components/Cart.js, src/Controller/OrderController.php, src/Sylius/Cart/RestaurantCartContext.php, tests/AppBundle/Sylius/Cart/RestaurantCartContextTest.php
Fixes: https://github.com/coopcycle/coopcycle-web/issues/3689 
Fixes: https://github.com/coopcycle/coopcycle-web/issues/3690
=> fix group order

src/Utils/RestaurantStats.php
=> Export order data based on fulfill event date.

js/app/foodtech/dashboard/components/OrderCard.js, js/app/foodtech/dashboard/redux/reducers.js, src/Resources/config/serialization.yml, templates/_partials/order/summary.html.twig
Closes #3641 
https://demo.coopcycle.org/admin/orders
https://demo.coopcycle.org/admin/foodtech/dashboard/2023-05-12
https://demo.coopcycle.org/admin/restaurants/124/dashboard
- Restaurant Dashboard
<br />
<br />
- Admin Foodtech Dashboard
<br /><br />
- Admin orders
=> Add comments icon to alert administrators about existing comments in orders

app/config/services.yml, src/Serializer/DeliveryNormalizer.php, src/Service/Tile38Helper.php
=> Add property with messenger location

src/Action/Delivery/Create.php, src/Entity/Delivery.php
=> Allow to create order from delivery in API context

app/config/message_bus/task.yml, features/tasks.feature, js/app/dashboard/components/ContextMenu.js, js/app/dashboard/components/Modals.js, js/app/dashboard/components/RescheduleTask.js, js/app/dashboard/components/Task.js, js/app/dashboard/components/TaskModalContent.js, js/app/dashboard/components/TaskRescheduleModalContent.js, js/app/dashboard/redux/actions.js, js/app/dashboard/redux/middlewares.js, js/app/dashboard/redux/reducers.js, js/app/i18n/locales/en.json, js/app/i18n/locales/fr.json, src/Action/Task/Base.php, src/Action/Task/Reschedule.php, src/Domain/Task/Command/Reschedule.php, src/Domain/Task/Event/TaskRescheduled.php, src/Domain/Task/Handler/RescheduleHandler.php, src/Entity/Task.php, src/Service/ActivityManager.php, src/Service/TaskManager.php, translations/messages.en.yml, translations/messages.fr.yml
https://github.com/coopcycle/coopcycle-web/assets/5613584/b1d3d524-21c8-4a9b-bc64-06574516d0a0
=> Task reschedule

src/Domain/Order/Reactor/CreateTasks.php, src/Sylius/Order/OrderInterface.php, tests/AppBundle/Domain/Order/Reactor/CreateTasksTest.php
This change will be needed to see in the app the payment method information.
https://github.com/coopcycle/coopcycle-app/issues/1542
=> Add payment method to task metadata

features/foodtech.feature, features/orders.feature, features/orders_adhoc.feature, src/Resources/config/serialization.yml
Fixes: coopcycle/coopcycle-app#1548
=> Order events

app/DoctrineMigrations/Version20231009114227.php, features/recurrence_rules.feature, js/app/dashboard/components/RecurrenceRule.js, js/app/dashboard/components/RecurrenceRuleModalContent.js, js/app/dashboard/redux/actions.js, js/app/i18n/locales/de.json, js/app/i18n/locales/en.json, js/app/i18n/locales/es.json, js/app/i18n/locales/fr.json, js/app/i18n/locales/it.json, src/Entity/Task/RecurrenceRule.php, src/Resources/config/doctrine/Task.RecurrenceRule.orm.xml
Recurrence rules can now be named
Recurrence rule's positions can be reordered
https://github.com/coopcycle/coopcycle-web/assets/5613584/1005ea66-691b-49a8-85bd-ac8db36178d7
=> recurrence rule enhancements :sparkles: 

app/DoctrineMigrations/Version20231107131157.php, src/Doctrine/EventSubscriber/TaskSubscriber.php, tests/AppBundle/Doctrine/EventSubscriber/TaskSubscriberFunctionalTest.php, tests/AppBundle/Doctrine/EventSubscriber/TaskSubscriberTest.php
=> Cancel order when all linked tasks are cancelled

composer.json, composer.lock, src/Entity/Listener/OrderListener.php, src/Entity/Sylius/OrderRepository.php, src/Resources/config/doctrine/Sylius.Order.orm.xml, src/Sylius/Order/OrderNumberAssigner.php
=> Use base32 for order numbers

src/Controller/OrderController.php
Added extra logs to debug issues when a customer completes a payment on Stripe, but it's not reflected on Coopcycle. That leads to issues such as:
https://github.com/coopcycle/coopcycle-web/issues/3688
https://github.com/coopcycle/coopcycle-app/issues/1603
So far, my main hypothesis is that there are cases when the payment form is considered invalid, even if the Stripe payment intent is authorised. These logs should help us understand why it happens if that's indeed the case.
=> added: extra logs to debug stripe payment issues

app/config/services.yml, app/config/services/twig.yml, features/foodtech.feature, features/orders.feature, features/restaurants.feature, features/shops.feature, src/Assets/PlaceholderImageResolver.php, src/Serializer/RestaurantNormalizer.php, src/Twig/AssetsRuntime.php, src/Twig/LocalBusinessRuntime.php, src/Utils/RestaurantDecorator.php
=> Add tags, badges & banner images to API responses

src/Action/Cart/CreateSession.php, src/Api/DataTransformer/CartSessionInputDataTransformer.php, src/Controller/OrderController.php, src/Controller/RestaurantController.php, src/Service/LoggingUtils.php, src/Service/NullLoggingUtils.php, src/Sylius/Cart/RestaurantCartContext.php, src/Sylius/Cart/SessionSubscriber.php, src/Sylius/OrderProcessing/OrderFeeProcessor.php, src/Sylius/OrderProcessing/OrderVendorProcessor.php, templates/order/index.html.twig, tests/AppBundle/Controller/RestaurantControllerTest.php, tests/AppBundle/Sylius/Cart/RestaurantCartContextTest.php, tests/AppBundle/Sylius/OrderProcessing/OrderFeeProcessorTest.php, tests/AppBundle/Sylius/OrderProcessing/OrderOptionsFeeProcessorTest.php, tests/AppBundle/Sylius/OrderProcessing/OrderVendorProcessorTest.php
Continuation of https://github.com/coopcycle/coopcycle-web/pull/3908
=> stripe issues, more logs

app/config/config.yml, app/config/message_bus/order.yml, app/config/services/validators.yml, src/Action/Order/LoopeatFormats.php, src/Domain/Order/Handler/AcceptOrderHandler.php, src/Exception/LoopeatInsufficientStockException.php, src/Validator/Constraints/LoopeatStock.php, src/Validator/Constraints/LoopeatStockValidator.php, translations/validators.en.yml, translations/validators.fr.yml
=> Validate stock of zero waste containers before accepting.

js/app/components/Autocomplete.js, js/app/i18n/locales/en.json, js/app/i18n/locales/fr.json, js/app/widgets/Search.js, src/Controller/AdminController.php, src/Entity/Sylius/OrderRepository.php, templates/admin/orders.html.twig
=> Improve orders search

assets/css/utils.scss, js/app/dashboard/components/ImportModalContent.js, js/app/dashboard/components/LeafletMap.js, js/app/dashboard/components/MapProxy.js, js/app/dashboard/components/RightPanel.js, js/app/dashboard/components/Task.js, js/app/dashboard/components/TaskList.js, js/app/dashboard/components/TaskLists.js, js/app/dashboard/components/Tour.js, js/app/dashboard/components/UnassignedTasks.js, js/app/dashboard/components/UnassignedTours.js, js/app/dashboard/components/context-menus/TasksContextMenu.js, js/app/dashboard/redux/__tests__/actions.test.js, js/app/dashboard/redux/__tests__/contextMenu.test.js, js/app/dashboard/redux/__tests__/handleDrag.test.js, js/app/dashboard/redux/__tests__/storeFixture.js, js/app/dashboard/redux/actions.js, js/app/dashboard/redux/reducers.js, js/app/dashboard/redux/selectors.js, js/app/dashboard/redux/utils.js, js/app/i18n/locales/en.json, js/app/i18n/locales/fr.json, js/shared/src/logistics/redux/selectors.js
This PR introduce the following changes :
- **validate multiselected tasks : can only select tasks in the same tour and same rider (or unassigned)**
- **disable right-click context menu when task is in the tour**
And the following small clean-ups
- highlight task(s) on the right panel when you click marker on the map
- animated loader on task/tour loading
- use function based components for UnassignedTours
- use function based components for TaskList
- move the <Draggable> component wrapper to child component to avoid repetition (for example <Draggable> is now in <Task> component, not 3 times in UnassignedTasks, Tasklist, Tour)
=> Tours fixes 1

js/app/dashboard/components/context-menus/TasksContextMenu.js, js/app/dashboard/redux/__tests__/actions.test.js, js/app/dashboard/redux/actions.js, js/app/dashboard/redux/handleDrag.js, js/app/dashboard/redux/utils.js, js/app/i18n/locales/en.json, js/app/i18n/locales/fr.json
=> Enable highlight even if no action

src/Entity/Task.php, src/Serializer/TaskNormalizer.php
issue #4086
improve query time and reduce doctrine SQLs
before
after
=> clean: use custom query to get package on "Tasks" endpoint

features/deliveries.feature, src/Api/EventSubscriber/DeliverySubscriber.php, src/Service/DeliveryManager.php, tests/Behat/FeatureContext.php
=> fix: set pickup from store on POST_DESERIALIZE not PRE_VALIDATE

app/DoctrineMigrations/Version20240423125407.php, assets/css/utils.scss, features/deliveries.feature, js/app/admin/restaurants.js, js/app/i18n/locales/en.json, js/app/i18n/locales/fr.json, js/app/store/form.js, js/app/store/list.js, src/Api/EventSubscriber/DeliverySubscriber.php, src/Api/EventSubscriber/SoftDeletedSubscriber.php, src/Controller/AdminController.php, src/Controller/Utils/StoreTrait.php, src/Doctrine/EventSubscriber/PostSoftDeleteSubscriber.php, src/Doctrine/EventSubscriber/ShopsEventsForTypesenseSubscriber.php, src/Entity/LocalBusiness.php, src/Entity/Store.php, src/Form/StoreType.php, src/Resources/config/doctrine/LocalBusiness.orm.xml, src/Resources/config/doctrine/Store.orm.xml, src/Service/DeliveryManager.php, templates/_partials/restaurant/list.html.twig, templates/admin/restaurants.html.twig, templates/store/form.html.twig, templates/store/list.html.twig, tests/Behat/FeatureContext.php, webpack.config.js
- add "deletedAt" field in table store
- add a "delete" button on store detail page (with confirmation pop up)
- remove "owner" link with store on soft delete
- hides store on stores list after soft delete
#4003 
and
- add the ability to delete store from stores list
- add the ability to delete restaurant from restaurants list
=> feat: add the ability to soft delete stores

.github/workflows/test.yml, app/config/config.yml, src/Doctrine/Functions/JsonBuildObject.php, src/Sylius/Product/LazyProductVariantResolver.php, tests/AppBundle/Sylius/Product/LazyProductVariantResolverTest.php
=> Optimize variant resolver

js/app/dashboard/redux/utils.js
=> fix: show unassigned tasks when filtering out courier

assets/css/styles.scss, js/app/checkout/summary.js, js/app/restaurant/item.js, js/app/widgets/StripePaymentForm.js, js/app/widgets/button.js, templates/order/index.html.twig, templates/order/payment.html.twig, templates/public/adhoc_order.html.twig, templates/public/order.html.twig
Fixes:
- https://github.com/coopcycle/coopcycle-web/issues/4214
- https://github.com/coopcycle/coopcycle-web/issues/4140
=> address page: order button

src/Entity/Sylius/Order.php, src/Form/Order/CartType.php, src/Serializer/JsonLd/OrderNormalizer.php, src/Sylius/Order/OrderInterface.php, src/Sylius/OrderProcessing/OrderFeeProcessor.php, src/Utils/OrderTimeHelper.php, src/Utils/ShippingDateFilter.php, src/Validator/Constraints/ShippingAddressValidator.php, tests/AppBundle/Sylius/OrderProcessing/OrderFeeProcessorTest.php, tests/AppBundle/Utils/OrderTimeHelperTest.php, tests/AppBundle/Utils/ShippingDateFilterTest.php, tests/AppBundle/Validator/ShippingAddressValidatorTest.php
In [this discussion](https://github.com/coopcycle/coopcycle-web/discussions/4302) you can find the idea behind these changes.
=> New method to get setup vendor information

js/app/register/index.js, src/Controller/UserController.php
#4296 
https://github.com/coopcycle/coopcycle-web/assets/4819244/c5cbacb6-6253-49f0-b144-5dabb16f892a
https://github.com/coopcycle/coopcycle-web/assets/4819244/d12635af-aba8-434c-953c-a128710d97ae
=> Check if email exists before submit registration form

js/app/foodtech/dashboard/components/Column.js, js/app/foodtech/dashboard/components/Dashboard.js, js/app/foodtech/dashboard/index.js, js/app/foodtech/dashboard/index.scss, js/app/foodtech/dashboard/redux/actions.js, js/app/foodtech/dashboard/redux/middlewares.js, js/app/foodtech/dashboard/redux/reducers.js, js/app/foodtech/dashboard/redux/selectors.js, js/app/foodtech/dashboard/redux/store.js
=> added: ability to collapse columns

src/Validator/Constraints/GoogleApiKeyValidator.php, translations/validators.en.yml, translations/validators.fr.yml
=> display Google API key validation error to a user

js/app/dashboard/redux/middlewares.js
=> Fix for assignment bug when dispatching on two different tabs on two different days (reported by Naofood)

js/app/dashboard/components/MapProxy.js
=> Fix crash when setting "use avatar color" to Yes

.github/workflows/build.yml, .github/workflows/test.yml, composer.json, composer.lock, docker-compose.yml, docker/php/Dockerfile, docker/php_worker/Dockerfile, tests/AppBundle/Service/GeofencingTest.php, tests/AppBundle/Utils/OrdersRateLimitFunctionalTest.php
=> Upgrade PHP from 8.2 to 8.3

js/app/register/index.js, templates/_partials/profile/definition_password_for_classical_users.html.twig, templates/_partials/profile/personal_information_form.html.twig, templates/bundles/NucleosProfileBundle/Registration/register_content.html.twig, translations/messages.en.yml, translations/messages.es.yml, translations/messages.fr.yml
#4396 
https://github.com/coopcycle/coopcycle-web/assets/4819244/89d02c23-5f92-4710-8e09-8457f8ae5608
https://github.com/coopcycle/coopcycle-web/assets/4819244/d6ae4ffe-f57b-40ff-a33c-4d193c8311fe
=> Propose login when registration email exists

js/app/dashboard/components/LeafletPopupContent.js, js/app/dashboard/components/MapProxy.js, js/app/dashboard/components/RightPanel.js, js/app/dashboard/dashboard.scss, js/app/dashboard/index.js
Deprecated render is still used in other popups on the map :      
- rider    
- restaurant pickup group
=> Use React18 createRoot in dispatch

js/app/dashboard/components/MapProxy.js, js/app/dashboard/index.js, js/app/i18n/locales/de.json, js/app/i18n/locales/en.json, js/app/i18n/locales/es.json, js/app/i18n/locales/fr.json, js/app/i18n/locales/it.json
=> Fix : in dispatch, save use_avatar_colors between refresh

assets/css/styles.scss, templates/menu.html.twig
issue #4124 
desktop
tablet size
mobile
=> Add "dispatch" next to the top bar lock icon to go to admin

js/app/dashboard/components/RightPanel.js, js/app/dashboard/components/TaskGroup.js, js/app/dashboard/components/TaskList.js, js/app/dashboard/components/TaskLists.js, js/app/dashboard/components/context-menus/TasksContextMenu.js, js/app/dashboard/dashboard.scss, js/app/dashboard/index.js, js/app/dashboard/redux/actions.js, js/app/dashboard/redux/selectors.js, js/app/dashboard/redux/uiReducers.js, js/app/dashboard/redux/utils.js, package-lock.json, package.json
when selecting a bunch of tasks :
- open all related unassigned groups
- open all related tours
- open all related tasklists
scrollIntoView of the first task
=> Show task(s) in the right hand columns when selecting a task on the map

app/DoctrineMigrations/Version20240612162133.php, app/DoctrineMigrations/Version20240625145913.php, app/config/config.yml, app/config/services/serializer.yml, assets/react/controllers/Store/TimeSlot.jsx, composer.lock, features/fixtures/ORM/stores.yml, features/stores.feature, js/app/i18n/locales/en.json, js/app/i18n/locales/fr.json, src/Controller/Utils/StoreTrait.php, src/Entity/Store.php, src/Entity/StoreTimeSlot.php, src/Entity/TimeSlot.php, src/Form/StoreType.php, src/Form/TaskType.php, src/Resources/config/doctrine/Store.orm.xml, src/Resources/config/doctrine/StoreTimeSlot.orm.xml, src/Serializer/PatchAwareStoreNormalizer.php, templates/form/store.html.twig, templates/store/form/_partials/settings.html.twig
Time slots are now managed via a self-contained React component.
=> Allow dispatch to reorder timeslots on Store settings

composer.json, composer.lock, features/fixtures/ORM/stores.yml, src/Command/SyncTransportersCommand.php, tests/AppBundle/Transporter/SyncTransportersCommandTest.php
In this PR:
- Add support for SFTP connection.
- Add support for multiple sync filesystems (in & out) per transporter
- Add tests
:exclamation: Need to update transporter config for Dinan & Annecy before deploying this -> https://github.com/coopcycle/coopcycle-ops/pull/90
=> Transporters: Add support for multiple synchronisation mechanism

js/app/components/core/LoadingIcon.js
#4519,
Updated LoadingIcon components to use new loader class `<span className="loader loader--dark"></span>`
=> chore: Update LoadingIcon component to use new loader class #4519

js/app/delivery/form.js
Fixes: https://coopcycle.sentry.io/issues/5639698367/?project=5294179&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D+coopcycle_app_name%3Ademo&referrer=issue-stream&statsPeriod=7d&stream_index=15&utc=true
=> added client-side validation for arbitrary price fields

features/deliveries_multi.feature, js/app/delivery/form.js, js/app/delivery/form.scss, js/app/forms/components/SuggestionModal.js, js/app/forms/delivery.js, js/app/forms/redux/suggestionsSlice.js, js/app/forms/redux/tasksSlice.js, js/app/i18n/locales/en.json, js/app/i18n/locales/fr.json, package-lock.json, package.json, src/Action/Delivery/SuggestOptimizations.php, src/Api/Dto/OptimizationSuggestion.php, src/Api/Dto/OptimizationSuggestions.php, src/Api/EventSubscriber/DeliverySubscriber.php, src/Entity/Delivery.php, src/Entity/Listener/TaskListener.php, src/Entity/Task.php, templates/delivery/form.html.twig
=> Suggest route optimization on delivery form

app/DoctrineMigrations/Version20240924080623.php, js/app/components/AddressAutosuggest.js, src/Action/TaskList/SetItems.php, src/Entity/Listener/DeliveryListener.php, src/Entity/Store.php, src/Form/LocalBusinessType.php, src/Form/StoreType.php, src/Resources/config/doctrine/Delivery.orm.xml, src/Resources/config/doctrine/Store.orm.xml, src/Service/TaskListManager.php, templates/store/form/_partials/settings.html.twig, translations/messages.de.yml, translations/messages.en.yml, translations/messages.es.yml, translations/messages.fr.yml, translations/messages.it.yml
=> Add the possibility to auto-assign orders from a store

src/Command/InitDemoCommand.php, src/Faker/it/RestaurantProvider.php
See #54
- Add Italian Faker provider 
- Fix Photon usage
- Add options to set lat/lng & skip admin creation
=> Improve demo command 

.gitignore, src/Command/ExportOrdersCommand.php, src/Entity/Sylius/Order.php, src/Utils/RestaurantStats.php, translations/messages.en.yml
Since the Foodtech and Lastmile shops are billed at different rates (yeah, I just figured that out thanks to @Atala), we need to include the shop types in the exports.
=> Add `applied_billing` in the exports

app/config/config.yml, js/app/admin/store/form.js, js/app/restaurant/fulfillment-methods.js, src/Controller/Utils/StoreTrait.php, src/Form/StoreType.php, src/Validator/Constraints/CheckDelivery.php, src/Validator/Constraints/CheckDeliveryValidator.php, templates/form/delivery_zone_picker.html.twig, templates/form/restaurant.html.twig, templates/form/store.html.twig, templates/store/form/_partials/settings.html.twig, translations/validators.en.yml, translations/validators.fr.yml
=> Allow limiting deliveries to a zone/distance for a store

composer.lock, tests/AppBundle/Transporter/SyncTransportersCommandTest.php
Fixes: https://github.com/coopcycle/coopcycle-web/issues/4692
=> Fixing Edifact REPORT generator

app/config/services.yml, app/config/services/forms.yml, src/Form/DataExportType.php, src/Spreadsheet/ColisActivDataExporter.php, translations/messages.en.yml, translations/messages.fr.yml
=> ColisActiv export add option to export all

src/MessageHandler/ExportTasksHandler.php, tests/AppBundle/MessageHandler/ExportTasksHandlerFunctionalTest.php
The old export was using CubeJS to perform the exports. I ported it to raw SQL.
=> full rework of `ExportTasksHandler`

app/config/config.yml, app/config/services.yml, src/Command/SyncTransportersCommand.php, src/Transporter/ImportFromPoint.php, tests/AppBundle/Transporter/SyncTransportersCommandTest.php
=> Improve logging for Transporter sync

src/EventListener/SeoListener.php, src/Twig/CoopCycleExtension.php, src/Twig/PageTitlePrefixResolver.php, templates/admin/dashboard_iframe.html.twig, templates/admin/deliveries.html.twig, templates/admin/foodtech_dashboard.html.twig, templates/admin/incidents.html.twig, templates/admin/orders.html.twig, templates/admin/restaurants.html.twig, templates/admin/settings.html.twig, templates/admin/stores.html.twig, templates/admin/users.html.twig, templates/base.html.twig, templates/delivery/item.html.twig, templates/order/service.html.twig, templates/store/layout.html.twig, templates/store/subscriptions/item.html.twig, translations/messages.de.yml, translations/messages.en.yml, translations/messages.es.yml, translations/messages.fr.yml
=> customise page titles

src/Command/BaseExportCommand.php, src/Command/ExportOrdersCommand.php, src/Entity/Sylius/OrderView.php, src/Utils/RestaurantStats.php, translations/messages.en.yml, translations/messages.fr.yml
- Add `incident_adjustements` on the CSV export
- Add `incidents` on the CSV
- This cell contains all the incident titles joined by `\n`
- Add support for `file://` protocol
```$ coopcycle:export:orders --target="file:///dev/stdout" --format=csv```
=> Update the orders export to take in account the incidents

assets/react/controllers/Delivery/DeliveryForm.jsx, js/app/components/delivery-form/DateRangePicker.js, js/app/components/delivery-form/SwitchTimeSlotFreePicker.js, js/app/components/delivery-form/Task.js, js/app/components/delivery-form/TimeSlotPicker.js, js/app/i18n/locales/en.json, js/app/i18n/locales/fr.json
Expected behavior :
- when pickup date changes, if drop(s) date is after change it to pickup date
- when pickup timeslot change, change drop timeslot
- when pickup timeslot choice change, if drop(s) date is after change it to pickup date
=> Feat : in beta delivery form synchronize dropoff dates when pickup date changes (timeslot and non-timeslot cases)

assets/react/controllers/Store/TimeSlot.jsx
Avoid a crash in the delivery form
=> In the store setting, when there is no default timeslot selected force select the first timeslot as default

src/Api/DataProvider/InvoiceLineItemCollectionDataProvider.php, src/Api/DataProvider/InvoiceLineItemGroupedByOrganizationCollectionDataProvider.php, src/Controller/AdminController.php, src/Controller/EmbedController.php, src/Entity/Sylius/OrderRepository.php, src/Sylius/Cart/SessionStorage.php
Uses 5 query less to load the cart from session
=> Feat: improve cart loading time

cypress/fixtures/components/address-autosuggest.yml, features/dispatch.feature, features/stores.feature, features/task_lists.feature, src/Entity/TaskList.php
Related issues:
* [coopcycle/coopcycle#234](https://github.com/coopcycle/coopcycle/issues/234)
* [coopcycle/coopcycle#198](https://github.com/coopcycle/coopcycle/issues/198)
Related PRs:
* https://github.com/coopcycle/coopcycle-app/pull/1985
---
The color is the one used to fill the username, like:
=> [PERTE-233] Added color to TaskList entity

src/Controller/PublicController.php
The bug was introduced in b942ecc9de when we added the "send payment link feature"
When we use the "embed delivery form" feature the payment form is shown, but the person already "paid" (payment without capture)
=> Fix for embedded delivery form : do not show payment form if payment is waiting for capture (authorized state)

.github/workflows/test_behat.yml, features/invoicing.feature, tests/Behat/FeatureContext.php
In those tests we use the Cypress fixtures files
=> Add tests for invoicing API

js/app/foodtech/dashboard/components/ModalContent.js, js/app/foodtech/dashboard/components/OrderItems.js, templates/admin/orders.html.twig
=> foodtech dashboard minimap

config/packages/monolog.yaml, config/packages/prod/monolog.yaml, config/packages/test/monolog.yaml, cypress/support/commands.js, src/Entity/Sylius/OrderItem.php, src/Sylius/Order/OrderItemInterface.php, templates/_partials/order/item.html.twig
- fix: keep the same order of order item adjustments
=> Mics improvements 2

features/orders.feature, features/restaurants.feature, features/shops.feature, features/stripe_payment_methods.feature
This reverts commit 633083d114ee3ee292328c680a1253db08db334f.
=> Fix: api tests
