coopcycle/coopcycle-web

app/DoctrineMigrations/Version20171007174720.php, app/DoctrineMigrations/Version20171009105937.php, features/fixtures/ORM/restaurants.yml, features/restaurants.feature, src/AppBundle/Command/InitDemoCommand.php, src/AppBundle/Command/Resources/menu.yml, src/AppBundle/Controller/AdminController.php, src/AppBundle/Controller/RestaurantTrait.php, src/AppBundle/Entity/Base/MenuItem.php, src/AppBundle/Entity/Menu/MenuCategory.php, src/AppBundle/Entity/Menu/MenuItem.php, src/AppBundle/Entity/Menu/MenuSection.php, src/AppBundle/Entity/Menu/Modifier.php, src/AppBundle/Entity/Model/Name/MethodsTrait.php, src/AppBundle/Entity/Order.php, src/AppBundle/Form/MenuCategoryType.php, src/AppBundle/Form/MenuType.php, src/AppBundle/Resources/config/serialization.yml, src/AppBundle/Resources/translations/messages.fr.yml, src/AppBundle/Resources/views/Admin/menuCategories.html.twig, src/AppBundle/Resources/views/Admin/newDelivery.html.twig, src/AppBundle/Resources/views/Admin/newMenuCategory.html.twig, src/AppBundle/Resources/views/Form/menu.html.twig, src/AppBundle/Resources/views/Restaurant/form-menu.html.twig, src/AppBundle/Resources/views/Restaurant/form.html.twig, src/AppBundle/Resources/views/admin.html.twig, src/AppBundle/Serializer/MenuSectionNormalizer.php
Naming things is hard 🙂
All menu subclasses have been moved to the `Entity\Menu` namespace. 
Now `Entity\MenuSection` is `Entity\Menu\MenuCategory`, which makes more sense.
Fixes #84 
Fixes #57
=> Refactor menu entities

app/config/config.yml, app/config/parameters.yml.dist, composer.json, docker-compose.yml, js/api/RedisClient.js, js/api/RedisRepository.js, js/api/dispatch/index.js, js/api/models/Courier.js, js/api/models/CourierPool.js, js/api/order/tracking.js, js/api/restaurant/panel.js, js/api/tracking/index.js, js/app/cart/Cart.jsx, js/tests/utils.js, package-lock.json, package.json
F*x #63 
I think we just need to redeploy each instance and it will be fine, as data are always polled from Postgres.
Note that I did a small trick to prefix `subscribe` calls.
<strike>Please don't merge I have still a [question about this change](https://github.com/NodeRedis/node_redis/issues/1286)</strike>
=> fix: add prefixes to Redis

.travis.yml, app/AppKernel.php, app/DoctrineMigrations/Version20171130230406.php, app/DoctrineMigrations/Version20171130231943.php, app/config/config.yml, app/config/services.yml, composer.json, composer.lock, features/fixtures/ORM/restaurants.yml, src/AppBundle/Command/InitDemoCommand.php, src/AppBundle/Entity/Base/MenuItem.php, src/AppBundle/EventListener/SyliusIdGeneratorSubscriber.php, src/AppBundle/Form/MenuItemType.php, src/AppBundle/Resources/translations/messages.fr.yml, src/AppBundle/Resources/views/Form/menu.html.twig, tests/AppBundle/BaseTest.php, tests/AppBundle/Utils/CartTest.php
The pull request introduces taxation with [Sylius](http://docs.sylius.org/en/latest/book/index.html). 
It contains the minimal stuff to parameterize taxes for each menu item. 
Once it is merged, we can add screens to manage taxes, and also calculate taxes in cart to create invoices. 
It also introduces a big change: **we need to switch to PHP 7.1**
In any case, the Docker machine is already in PHP 7.1 and support for PHP 7.0 ends in December 2017 🤓
Until we move to YAML mapping (see #155), tables will be prefixed by `sylius_`
=> Introduce taxation

app/DoctrineMigrations/Version20171201132329.php, assets/css/styles.scss, assets/css/utils.scss, assets/css/vars.scss, features/fixtures/ORM/restaurants.yml, features/restaurants.feature, js/app/restaurant/form.jsx, src/AppBundle/Command/InitDemoCommand.php, src/AppBundle/Controller/RestaurantController.php, src/AppBundle/Controller/RestaurantTrait.php, src/AppBundle/Entity/Restaurant.php, src/AppBundle/Entity/RestaurantRepository.php, src/AppBundle/Form/RestaurantType.php, src/AppBundle/Resources/translations/messages.en.yml, src/AppBundle/Resources/translations/messages.fr.yml, src/AppBundle/Resources/views/Restaurant/form.html.twig, src/AppBundle/Resources/views/Restaurant/index.html.twig, tests/AppBundle/Entity/RestaurantTest.php
Almost there still have an issue on error translations. I followed [this](http://symfony.com/doc/current/validation/translations.html) but it doesn't seem to work in the unit tests. If you have an idea @alexsegura.. (?)
PR add:
- possibility to disable/enable a restaurant
- admin and restaurant owner only can see the restaurant when disable (preview mode)
- restaurant is disabled by default at creation, there is a checkup before possibility to activate
=> Disable restaurant + restaurant checkup validation

js/app/cart/Cart.jsx, src/AppBundle/Controller/RestaurantController.php, src/AppBundle/Entity/RestaurantRepository.php, src/AppBundle/Resources/views/menu.html.twig, src/AppBundle/Utils/Cart.php
Enable the address selection on Cart .
<strike>I still have an issue before merging : 
- on restaurant list page the restaurant selection is based on a kilometer radius (`findNearby`)
- on cart picker the validation is done with the "real" distance by bike
So a delivery address which is valid on restaurants list page may not be valid on the cart selector. Which is terrible?</strike>
@alexsegura do you get the issue? do you have any idea to deal with it?
=> Select address on cart

app/DoctrineMigrations/Version20171203210138.php, app/config/services.yml, assets/css/styles.scss, js/app/autocomplete.jsx, js/app/delivery/form.jsx, js/app/delivery/pricing-rules.jsx, package-lock.json, package.json, src/AppBundle/Controller/AdminController.php, src/AppBundle/Entity/Delivery.php, src/AppBundle/Entity/Delivery/PricingRule.php, src/AppBundle/Form/AddressType.php, src/AppBundle/Form/DeliveryType.php, src/AppBundle/Form/PricingRuleSetType.php, src/AppBundle/Form/PricingRuleType.php, src/AppBundle/Resources/translations/messages.en.yml, src/AppBundle/Resources/translations/messages.fr.yml, src/AppBundle/Resources/views/Admin/deliveries.html.twig, src/AppBundle/Resources/views/Admin/deliveriesPricing.html.twig, src/AppBundle/Resources/views/Admin/newDelivery.html.twig, src/AppBundle/Resources/views/Form/delivery.html.twig, src/AppBundle/Resources/views/Form/pricingRuleSet.html.twig, src/AppBundle/Resources/views/admin.html.twig, src/AppBundle/Service/DeliveryManager.php, src/AppBundle/Service/OrderManager.php, src/AppBundle/Tests/Action/TestCase.php, src/AppBundle/Utils/PricingRuleSet.php, tests/AppBundle/Entity/Delivery/PricingRuleTest.php, tests/AppBundle/Service/DeliveryManagerTest.php, webpack.config.js
Here is the first draft to introduce delivery pricing calculation based on configurable rules 🚀
Rules are simple [expressions](https://symfony.com/doc/current/components/expression_language.html) stored in database. To calculate the delivery price, the `DeliveryPriceManager` loops on rules and applies the first one that matches.
**TODO**
I think we can merge this early before introducing vehicles.
=> Introduce delivery pricing

js/api/models/Courier.js, js/tests/dispatch.js
I changed three things in the 'should dispatch order to closest courier' test case:
- The error is now raised as long as the wrong courrier receive a message. Before we were checking that the message type was 'order', I don't think that this is useful and furthermore if we want to check the message type I think it should be delivery.
- I removed the createRandomOrder function from the beforeEach one. In some test case we were creating two random order because of that. I am may have missed something here, not 100 % sure I should have removed it.
- I changed the courier location, see below
For the rest it is pretty straightforward, we were choosing the delivery address as the origin point while we should have chosen the restaurant address.
=> Dispatch adress bug

app/config/routing.yml, js/app/delivery/list.jsx, src/AppBundle/Action/Me.php, src/AppBundle/Controller/AdminController.php, src/AppBundle/Controller/ProfileController.php, src/AppBundle/Controller/Utils/DeliveryTrait.php, src/AppBundle/Resources/translations/messages.en.yml, src/AppBundle/Resources/translations/messages.fr.yml, src/AppBundle/Resources/views/Admin/deliveries.html.twig, src/AppBundle/Resources/views/Profile/courierDeliveries.html.twig, src/AppBundle/Resources/views/_partials/Delivery/actions.html.twig, src/AppBundle/Resources/views/_partials/Delivery/list.html.twig, src/AppBundle/Resources/views/_partials/Delivery/modal.html.twig, webpack.config.js
A really simple implementation of manual dispatch. 
**Administrator** can assign couriers to deliveries.
**Courier** can see assigned deliveries assigned in personal account, and change the status. 
This is just a first step before adding more cool stuff, but we need this at least to display it in the native app. 
ping @couleurmate
=> Introduce manual dispatch.

app/DoctrineMigrations/Version20180220124056.php, assets/css/dashboard.scss, js/app/dashboard/app.js, js/app/dashboard/components/Task.js, js/app/dashboard/components/TaskGroup.js, js/app/dashboard/components/TaskList.js, js/app/dashboard/components/UserPanel.js, js/app/dashboard/components/UserPanelList.js, js/app/dashboard/store/actions.js, js/app/dashboard/store/reducers.js, src/AppBundle/Controller/AdminController.php, src/AppBundle/Entity/Task.php, src/AppBundle/Entity/Task/Group.php, src/AppBundle/Resources/translations/messages.fr.yml, src/AppBundle/Resources/views/Admin/dashboardIframe.html.twig, src/AppBundle/Serializer/TaskNormalizer.php
This PR introduces **task groups**: a task may belong to a group, to apply bulk actions on it. 
For now, groups can only be drag'n'dropped to assign all tasks at once. 
A new button allows to display grouped tasks, or all tasks at once. 
The drag'n'drop management has also been simplified: linked tasks are not grouped together via a DOM element, but they are highlighted when dragged.
=> Introduce task groups

src/AppBundle/Controller/Utils/RestaurantTrait.php, src/AppBundle/Resources/config/routing/admin.yml
When adding a temporary closure (under planning for a restaurant) no route for "success" was defined, throwing a ContextErrorException.
=> Fixed ContextErrorException when adding a temporary closure

app/DoctrineMigrations/Version20180508142437.php, app/DoctrineMigrations/Version20180509092646.php, app/DoctrineMigrations/Version20180509100908.php, app/config/services.yml, features/fixtures/ORM/restaurants.yml, features/restaurants.feature, src/AppBundle/Entity/Contract.php, src/AppBundle/Entity/Sylius/Order.php, src/AppBundle/Form/ContractType.php, src/AppBundle/Resources/config/doctrine/Contract.orm.yml, src/AppBundle/Resources/translations/messages.en.yml, src/AppBundle/Resources/translations/messages.es.yml, src/AppBundle/Resources/translations/messages.fr.yml, src/AppBundle/Resources/views/Form/restaurant.html.twig, src/AppBundle/Resources/views/Restaurant/form.html.twig, src/AppBundle/Serializer/JsonLd/OrderNormalizer.php, src/AppBundle/Service/OrderManager.php, src/AppBundle/Sylius/Order/AdjustmentInterface.php, src/AppBundle/Sylius/Order/OrderFactory.php, src/AppBundle/Sylius/Order/OrderInterface.php, src/AppBundle/Sylius/OrderProcessing/OrderFeeProcessor.php, src/AppBundle/Validator/Constraints/OrderValidator.php, tests/AppBundle/Service/OrderManagerTest.php, tests/AppBundle/StripeTrait.php, tests/AppBundle/Sylius/OrderProcessing/OrderFeeProcessorTest.php, tests/AppBundle/Validator/OrderValidatorTest.php
Administrators can now specify an amount that will be charged by the platform, independently from the amount that will be charge to the customer. 
This allows "offering" the delivery to the customer, while still charging something to the business. 
Also, you can now specify a percentage fee that will be calculated on the items total. 
Finally, the platform fees are now stored inside the order using an adjustment.
=> Platform fees

assets/css/dashboard.scss, js/app/dashboard/components/Task.js, src/AppBundle/Entity/Delivery.php, src/AppBundle/Resources/views/Admin/deliveries.html.twig, src/AppBundle/Serializer/DeliveryNormalizer.php, src/AppBundle/Serializer/TaskNormalizer.php
Use colors to show clearly linked tasks (a.k.a deliveries for the moment)
=> Improve list display for deliveries

app/config/services.yml, features/bootstrap/FeatureContext.php, features/fixtures/ORM/products.yml, features/fixtures/ORM/restaurants.yml, features/fixtures/ORM/sylius_locales.yml, features/orders.feature, features/restaurants.feature, src/AppBundle/Action/Restaurant/Menu.php, src/AppBundle/Entity/Restaurant.php, src/AppBundle/Entity/Sylius/Taxon.php, src/AppBundle/Resources/config/serialization.yml, src/AppBundle/Serializer/JsonLd/OrderNormalizer.php, src/AppBundle/Serializer/JsonLd/RestaurantMenuNormalizer.php, src/AppBundle/Serializer/RestaurantNormalizer.php
The menu is now serialized with options, to be able to display them on the app. 
It uses the [`menuAddOn`](http://pending.schema.org/menuAddOn) property. 
```json
{
"hasMenuSection":[
{
"name":"Pizzas",
"hasMenuItem":[
{
"@type":"MenuItem",
"name":"Pizza",
"description":null,
"identifier":"PIZZA",
"menuAddOn":[
{
"@type":"MenuSection",
"name":"Pizza topping",
"identifier":"PIZZA_TOPPING",
"hasMenuItem":[
{
"@type":"MenuItem",
"name":"Pepperoni",
"identifier":"PIZZA_TOPPING_PEPPERONI"
},
{
"@type":"MenuItem",
"name":"Extra cheese",
"identifier":"PIZZA_TOPPING_EXTRA_CHEESE"
}
]
}
]
}
]
},
{
"name":"Burger",
"hasMenuItem":[
{
"@type":"MenuItem",
"name":"Hamburger",
"description":null,
"identifier":"HAMBURGER"
}
]
}
]
}
```
Also, it is now possible to specify product options when creating an …
=> Refactor API to handle products & options

js/app/task/modal.js, src/AppBundle/Controller/AdminController.php, src/AppBundle/Entity/TaskEvent.php, src/AppBundle/Exception/PreviousTaskNotCompletedException.php, src/AppBundle/Form/TaskEventType.php, src/AppBundle/Form/TaskType.php, src/AppBundle/Resources/translations/messages.en.yml, src/AppBundle/Resources/translations/messages.es.yml, src/AppBundle/Resources/translations/messages.fr.yml, src/AppBundle/Resources/views/Form/taskModal.html.twig, src/AppBundle/Resources/views/_partials/Task/form.html.twig, src/AppBundle/Service/TaskManager.php
The current method is hacky & does not manage errors correctly.
This PR reuses `TaskCompleteType` with several submit buttons.
**TODO**
=> Manage task complete "the right way"

.travis.yml, app/DoctrineMigrations/Version20180622100900.php, assets/css/styles.scss, docker/nodejs/run-tests.sh, js/app/components/DeliveryZonePicker.jsx, js/app/components/RulePicker.jsx, js/app/components/RulePickerLine.jsx, js/app/delivery/pricing-rule-parser.js, js/tests/pricing-rule-parser.js, js/tests/utils.js, package-lock.json, package.json, src/AppBundle/Entity/Delivery/PricingRule.php, src/AppBundle/Entity/Restaurant.php, src/AppBundle/ExpressionLanguage/ZoneExpressionLanguageProvider.php, tests/AppBundle/Entity/Delivery/PricingRuleTest.php, tests/AppBundle/ExpressionLanguage/ZoneExpressionLanguageProviderTest.php
Fixes #384 
I also add a new `out_zone` function, which allows smart combinations like below, to detect when a delivery is between 2 zones
**TODO**
=> Allow distinguishing pickup & dropoff address in pricing rules

app/config/message_bus/order.yml, app/config/state_machine.yml, features/tasks.feature, js/api/tracking/index.js, js/app/dashboard/app.js, js/app/dashboard/store/reducers.js, src/AppBundle/Action/Task/Base.php, src/AppBundle/Action/Task/Done.php, src/AppBundle/Action/Task/Failed.php, src/AppBundle/Domain/Order/Reactor/CancelTasks.php, src/AppBundle/Domain/Order/Reactor/UpdateState.php, src/AppBundle/Domain/Task/Handler/MarkAsDoneHandler.php, src/AppBundle/Domain/Task/Handler/MarkAsFailedHandler.php, src/AppBundle/Entity/Task.php, src/AppBundle/Exception/TaskCancelledException.php
**Cancel tasks when an order is cancelled**
Previously, the tasks were left untouched. Now, they are cancelled properly. 
**Make sure a cancelled task cannot be marked as done/failed**
As tasks were still there even if the order was cancelled, a courier may complete the dropoff task anyway, triggering the capture of the payment. Now, cancelled task can't be completed. 
**Fix dashboard**
Also, I noticed newly created tasks were causing an error when dragged. This is fixed.
=> Handle order cancellation properly

app/config/services.yml, assets/css/styles.scss, js/app/widgets/Switch.js, js/app/widgets/index.js, src/AppBundle/Controller/AdminController.php, src/AppBundle/EventListener/MaintenanceListener.php, src/AppBundle/Form/MaintenanceType.php, src/AppBundle/Form/SettingsType.php, src/AppBundle/Form/StripeLivemodeType.php, src/AppBundle/Resources/translations/messages.en.yml, src/AppBundle/Resources/translations/messages.es.yml, src/AppBundle/Resources/translations/messages.fr.yml, src/AppBundle/Resources/views/Admin/settings.html.twig, src/AppBundle/Resources/views/_partials/maintenance.html.twig, src/AppBundle/Resources/views/admin.html.twig, src/AppBundle/Resources/views/base.html.twig, src/AppBundle/Resources/views/maintenance.html.twig, src/AppBundle/Service/SettingsManager.php, src/AppBundle/Twig/CoopCycleExtension.php, src/AppBundle/Twig/MaintenanceResolver.php
In maintenance mode, all requests return a 503, except for administrators, who can continue to browse the site. This will allow, for example, to disable Stripe live mode, to make some tests with fake credit cards. 
---
This is also linked with Stripe live mode. If the platform is in live mode, switching to test mode automatically switches to maintenance. 
--- 
Finally, it is now impossible to switch to live mode without the keys configured.
=> Maintenance mode

assets/css/main.scss, assets/css/ripple.scss, assets/css/styles.scss, js/app/cart/Cart.jsx
- Show "status" icon on the left.
- Display error text on the heading.
- Add "ripple effect" when there is an error.
=> Improve mobile cart.

README.md
Setup might not be as straightforward as running `make install` for newcomers. Adding more instructions regarding the Google Maps API and file permissions on Linux can help them set up a test environment more easily the first time.
Issue #436
=> More instructions for newcomers

app/Resources/FOSUserBundle/views/Registration/check_email.html.twig, app/Resources/FOSUserBundle/views/Registration/confirmed.html.twig, src/AppBundle/Resources/translations/FOSUserBundle.en.yml, src/AppBundle/Resources/translations/FOSUserBundle.es.yml, src/AppBundle/Resources/translations/FOSUserBundle.fr.yml
Basically this is just template customization. 
The templates where not customized at all, and were using the `profile.html.twig` layout, which could lead to confusion for the user.
=> Improve registration.

app/DoctrineMigrations/Version20190216143748.php, app/config/config.yml, features/bootstrap/FeatureContext.php, features/checkout.feature, features/login.feature, js/app/cart/components/AddressModal.js, js/app/cart/components/Cart.js, js/app/cart/redux/actions.js, js/app/cart/redux/reducers.js, js/app/restaurant/index.js, js/app/utils/GoogleMaps.js, src/AppBundle/Controller/IndexController.php, src/AppBundle/Controller/RestaurantController.php, src/AppBundle/Controller/Utils/UserTrait.php, src/AppBundle/Form/Order/CartType.php, src/AppBundle/Resources/views/_partials/restaurant/list_thumbnail.html.twig, src/AppBundle/Resources/views/index/index.html.twig, src/AppBundle/Resources/views/restaurant/index.html.twig, src/AppBundle/Resources/views/restaurant/list.html.twig
When a customer is logged in & has saved addresses, they are displayed in the autosuggest. 
When selected, the address won't be re-created. 
Also, the migration will deduplicate customer addresses that have the same geo coordinates.
=> Reintroduce "preferred addresses" 

app/config/message_bus/order.yml, app/config/services.yml, app/config/services/forms.yml, js/app/cart/components/CartTotal.js, src/AppBundle/Command/SetupCommand.php, src/AppBundle/Controller/AdminController.php, src/AppBundle/Controller/OrderController.php, src/AppBundle/Domain/Order/Reactor/ModifyPromotionsUsage.php, src/AppBundle/Form/Checkout/CheckoutAddressType.php, src/AppBundle/Form/Extension/PromotionCouponTypeExtension.php, src/AppBundle/Resources/translations/messages.en.yml, src/AppBundle/Resources/translations/messages.es.yml, src/AppBundle/Resources/translations/messages.fr.yml, src/AppBundle/Resources/views/_partials/order/items.html.twig, src/AppBundle/Resources/views/admin/nav.html.twig, src/AppBundle/Resources/views/admin/promotion.html.twig, src/AppBundle/Resources/views/admin/promotion_coupon.html.twig, src/AppBundle/Resources/views/admin/promotions.html.twig, src/AppBundle/Resources/views/order/index.html.twig, src/AppBundle/Serializer/CartNormalizer.php, src/AppBundle/Sylius/OrderProcessing/OrderFeeProcessor.php, src/AppBundle/Sylius/OrderProcessing/OrderPromotionProcessor.php, src/AppBundle/Sylius/Promotion/Modifier/OrderPromotionsUsageModifier.php
For now, we only support coupon-based promotions. 
A unique promotion `FREE_DELIVERY` is created by default. 
The admin interface is simplified and only allows to add coupons to the `FREE_DELIVERY` promotion. 
**TODO**
=> Introduce coupon-based promotions

app/DoctrineMigrations/Version20190711184422.php, app/DoctrineMigrations/Version20190711205815.php, app/config/services/forms.yml, composer.json, composer.lock, js/app/forms/delivery.js, src/AppBundle/Controller/AdminController.php, src/AppBundle/Entity/Store.php, src/AppBundle/Entity/TimeSlot.php, src/AppBundle/Entity/TimeSlot/Choice.php, src/AppBundle/Form/DeliveryEmbedType.php, src/AppBundle/Form/DeliveryType.php, src/AppBundle/Form/StoreType.php, src/AppBundle/Form/TimeSlotChoiceType.php, src/AppBundle/Form/TimeSlotType.php, src/AppBundle/Resources/config/doctrine/Store.orm.yml, src/AppBundle/Resources/config/doctrine/TimeSlot.Choice.orm.yml, src/AppBundle/Resources/config/doctrine/TimeSlot.orm.yml, src/AppBundle/Resources/translations/messages.en.yml, src/AppBundle/Resources/translations/messages.fr.yml, src/AppBundle/Resources/views/admin/nav.html.twig, src/AppBundle/Resources/views/admin/time_slot.html.twig, src/AppBundle/Resources/views/admin/time_slots.html.twig, src/AppBundle/Resources/views/delivery/form.html.twig, src/AppBundle/Resources/views/form/delivery.html.twig, src/AppBundle/Resources/views/form/time_slot.html.twig, src/AppBundle/Resources/views/store/form.html.twig, src/AppBundle/Utils/TimeSlotChoiceWithDate.php, tests/AppBundle/Entity/TimeSlot/ChoiceTest.php, tests/AppBundle/Entity/TimeSlotTest.php
See #594
This pull request introduces a **fairly simple** mechanism to create time slots. 
A time slot is just a list of time choices.
Time slots can be linked to stores. 
If a store is configured with a time slot (optional), then time slots are proposed instead of free time choice.
The time slot choices are aware of the working days.
=> Introduce configurable Time Slots

app/config/services.yml, src/AppBundle/Controller/EmbedController.php, src/AppBundle/Controller/PublicController.php, src/AppBundle/Domain/Order/Reactor/CapturePayment.php, src/AppBundle/Domain/Order/Reactor/PickOrDrop.php, src/AppBundle/Form/DeliveryEmbedType.php, src/AppBundle/Resources/views/embed/delivery/start.html.twig, src/AppBundle/Resources/views/embed/delivery/summary.html.twig, src/AppBundle/Resources/views/public/order.html.twig
This pull request changes the workflow of the embed form, i.e the customer must pay beforehand. 
Of course, we use authorize/capture mechanism to allow refusing orders.
=> Pay beforehand in embed form

src/AppBundle/Utils/TaskSpreadsheetParser.php, tests/AppBundle/Resources/spreadsheet/tasks.semicolon.csv, tests/AppBundle/Utils/TaskSpreadsheetParserTest.php
Fixes #734 
User request was that CSV files using semicolon as separator should be supported.
The [Spout Libary](https://github.com/box/spout) is used for reading CSV files, which is expecting the delimiter to be set if it is not comma (default).
I added a short logic to detect the delimiter (most used character in CSV headline) in the CSV file and setting the delimiter in the reader.
Test for CSV with semicolon was added.
The following separators are supported now and will be auto-detected: comma, semicolon, tab, pipe
=> Add CSV delimiter detection and set delimiter for CSV reader

.circleci/config.yml, Makefile, docker-compose.yml, docker/nginx/conf.d/default.conf, docker/nginx_test/conf.d/default.conf, docker/osrm/Dockerfile, docker/php/Dockerfile
See #789 #436
On Linux, there are problems with the mounted volumes which lead to permission issues. 
Basically, the volumes are mounted as `root` on the host machine.
See moby/moby#2259 & #moby/moby#3124
This pull request is another attempt to fix this. 
- Use `/var/www/html` as the mount folder as in base PHP image (b35c8b0)
- Run PHP-FPM as `root` (c93f2d8)
- Stop creating directories from the host machine (8d9ed69)
Also, it uses CircleCI to test the Docker environment works
=> Fix Docker on Linux, introduce CircleCI

app/config/services.yml, src/AppBundle/Service/RemotePushNotificationManager.php, tests/AppBundle/Service/RemotePushNotificationManagerTest.php
This change would allow android app to handle 'notifications' (if they are sent as 'data-only' messages) in the background and later on (when implemented on the app side) display a notifcation to the user locally without relying on firebase SDK, which gives the app more flexibility. 
This change should not affect current app users, because current version does not handle 'data-only' messages at all, and in a new version: 
- "tasks:changed" event would be handled the same way as now
- "order:created" event would be handled the same in the foreground and in the background a user would see a current notification + the app would be opened if possible (only on android)
=> android: send both 'notification+data' and 'data-only' (notification) messages

docker-compose.yml
A lot of the variables already declared in .env were not being used to build the docker instance, resulting in database and minio conflicts.
=> Standardize docker-compose and integrate with .env variables

app/DoctrineMigrations/Version20200825162252.php, app/DoctrineMigrations/Version20200826135116.php, src/Controller/AdminController.php, src/Controller/Utils/RestaurantTrait.php, src/Domain/Order/Command/Refund.php, src/Domain/Order/Handler/RefundHandler.php, src/Entity/Refund.php, src/Entity/Sylius/Order.php, src/Entity/Sylius/Payment.php, src/Form/PaymentType.php, src/Resources/config/doctrine/Refund.orm.xml, src/Resources/config/doctrine/Sylius.Payment.orm.xml, src/Resources/translations/messages.ca.yml, src/Resources/translations/messages.cs.yml, src/Resources/translations/messages.de.yml, src/Resources/translations/messages.en.yml, src/Resources/translations/messages.es.yml, src/Resources/translations/messages.fr.yml, src/Resources/translations/messages.it.yml, src/Resources/translations/messages.pl.yml, src/Resources/translations/messages.pt-BR.yml, src/Service/OrderManager.php, src/Service/StripeManager.php, src/Sylius/Payment/RefundTrait.php, src/Sylius/Payment/StripeTrait.php, templates/order/_partials/payment_form.html.twig, templates/restaurant/_partials/refunds.html.twig, templates/restaurant/stats.html.twig, tests/AppBundle/Domain/Order/Handler/RefundHandlerTest.php, tests/AppBundle/Entity/Sylius/PaymentTest.php
Fixes #1447
When creating a refund, it is now possible to specify which party is responsible for the incident. The checkbox to refund application fee has been deprecated because it was causing confusion & problems. 
A new tab is available on the restaurant stats screen, listing the refunds, and showing the total amount due by the platform to the business for the refunds (when the platform is reponsible for the incident)
=> Improve refunds

app/DoctrineMigrations/Version20200915100034.php, app/config/services/forms.yml, features/bootstrap/FeatureContext.php, features/tasks.feature, js/app/dashboard/components/Task.js, js/app/dashboard/components/TaskModalContent.js, js/app/delivery/task-list.js, js/app/utils/multi-select.js, src/Controller/AdminController.php, src/Doctrine/EventSubscriber/OrganizationSubscriber.php, src/Entity/Task.php, src/Form/AttachToOrganizationType.php, src/Resources/config/doctrine/Task.orm.xml, src/Resources/translations/messages.en.yml, templates/admin/tasks.html.twig, webpack.config.js
Fixes #1402
Under the hood, this pull request introduces Organizations (#1311) as the top level entity to represent a customer. 
Technically, tasks are attached to an Organization, and Stores & Restaurants too. However, the user interface still shows Stores/Restaurants, for backward compatibility. 
**TODO**
This introduces a new view for tasks as a list, where it's possible to attach tasks to stores
--- 
On the dashboard, when the task is attached to an organization (a store or a restaurant), it is displayed like this:
=> Attach tasks to organizations

Makefile
Related to issues #436 and #141 
Notice that #141 is already fixed with `make migrations-migrate`
But `make fresh` basically helps cleaning up everything docker for a fresh install.
=> Add make fresh for cleaning up

src/Spreadsheet/AbstractSpreadsheetParser.php, src/Spreadsheet/DeliverySpreadsheetParser.php, src/Spreadsheet/ProductSpreadsheetParser.php, src/Spreadsheet/TaskSpreadsheetParser.php, tests/AppBundle/Spreadsheet/TaskSpreadsheetParserTest.php
This PR is the follow up of  #681. It allows use of both "technical" and "meaningful" label in header of task import spreadsheet (i.e. "address.streetAddress", "address", "adress.latlng" and "latlong"). 
One must still use either address or geocoordinates, but not both at the same time, though.
=> Harmonizing task export and import

translations/messages.en.yml
In British English, the term `Holidays` conveys the right meaning instead of `Planning`.
=> Update wording Planning → Holidays

src/Command/SetupCommand.php
The PR add cash payment method in Argentina instances
=> add argentina cash-delivery-option

js/app/delivery/embed-start.js, js/app/delivery/form.js, js/app/delivery/form.scss, js/app/forms/delivery.js, src/Controller/Utils/StoreTrait.php, src/Form/DeliveryEmbedType.php, src/Form/DeliveryType.php, src/Form/TaskType.php, templates/delivery/form.html.twig, templates/embed/delivery/start.html.twig, templates/form/delivery.html.twig, templates/form/delivery_embed.html.twig
This is an intermediary pull request for #2610
It removes the `pickup`/`dropoff` properties from the form, and manages it as an array of tasks.
=> Use a form collection in DeliveryType

app/DoctrineMigrations/Version20210723161106.php, features/fixtures/ORM/recurrence_rules.yml, features/recurrence_rules.feature, src/Action/Task/RecurrenceRuleBetween.php, src/Entity/Delivery.php, src/Entity/DeliveryRepository.php, src/Resources/config/doctrine/Task.orm.xml, tests/AppBundle/Entity/DeliveryTest.php
See #2610 
When using recurrence rules, if the list of task starts with a pickup, a delivery will be created, that links the tasks together. 
This allows to:
=> Create delivery with multiple dropoffs when using recurrence rules

app/DoctrineMigrations/Version20211215104949.php, features/pricing_rules.feature, features/retail_prices.feature, js/app/delivery/embed-start.js, js/app/forms/delivery.js, src/Entity/Delivery.php, src/Entity/Package/PackageWithQuantity.php, src/Entity/Package/PackagesAwareInterface.php, src/Entity/Package/PackagesAwareTrait.php, src/Entity/Task.php, src/Entity/Task/Package.php, src/Form/DeliveryType.php, src/Form/PackageWithQuantityType.php, src/Form/TaskType.php, src/Resources/config/doctrine/Delivery.orm.xml, src/Resources/config/doctrine/Task.Package.orm.xml, src/Resources/config/doctrine/Task.orm.xml, src/Serializer/DeliveryNormalizer.php, src/Serializer/TaskNormalizer.php, templates/form/delivery.html.twig, templates/form/delivery_embed.html.twig, tests/AppBundle/Entity/DeliveryTest.php, tests/AppBundle/Entity/TaskTest.php
Now packages will be attached to **dropoff** tasks, instead of delivery. 
**TODO**
---
The `Delivery` class still exposes the same interface, but the implementation will now attach packages to the first dropoff task. 
```php
// Both are equivalent
$delivery->addPackageWithQuantity($small, 1);
$delivery->getDropoff()->addPackageWithQuantity($small, 1);
```
Same for the API, clients can still send `packages` at the delivery level, but they will be attached to the first dropoff task. 
```
POST /api/deliveries
{
"packages": [
{"type": "XL", "quantity": 2}
]
}
```
```
POST /api/deliveries
{
"dropoff": {
"packages": [
{"type": "XL", "quantity": 2}
}
]
}
```
---
=> Move packages at task level

app/config/services.yml, composer.json, composer.lock, src/Api/Filter/AssignedFilter.php, src/Api/Filter/TaskFilter.php, src/Command/CreateTasksCommand.php, src/Command/InitDemoCommand.php, src/Edenred/Authentication.php, src/Edenred/Client.php, src/Edenred/RefreshTokenHandler.php, src/LoopEat/Client.php, src/Service/Geocoder.php, src/Utils/RestaurantStats.php, src/Utils/SortableRestaurantIterator.php, tests/AppBundle/Edenred/ClientTest.php
At least now the project dependencies can be installed under PHP 8.x, and PHPStan returns no errors.
=> Allow Guzzle 7 & PHP 8

src/Controller/AdminController.php, templates/admin/users.html.twig, translations/messages.en.yml, translations/messages.es.yml, translations/messages.fr.yml
Closes #453 
This change doesn't delete the user from database. Instead, it changes the user's email to an anonymized one and sets user as disabled.
I don't know if it's a problem but the users list is showing enabled and disabled users, so when "delete" the user it still remains in the list but with the new anonymized email.
=> Allow to delete users in admin

features/deliveries_multi.feature, src/Entity/Delivery.php, src/Serializer/DeliveryNormalizer.php, tests/AppBundle/Entity/DeliveryTest.php
Following #3112, I realised that we didn't have a functional test that checks that the pickup task contains an aggregation of the packages and weight of the subsequent dropoffs. 
This pull request adds a test for that, and also allows to send a payload with multiple dropoffs.
=> Improve management of deliveries with multiple dropoffs.

app/DoctrineMigrations/Version20220217134929.php, app/config/services/forms.yml, js/app/forms/delivery.js, js/app/store/form.js, src/Entity/Store.php, src/Form/DeliveryType.php, src/Form/StoreType.php, src/Form/TaskType.php, src/Resources/config/doctrine/Store.orm.xml, templates/form/delivery.html.twig, templates/form/store.html.twig, templates/store/form/_partials/settings.html.twig, translations/messages.en.yml, translations/messages.fr.yml
Fixes #3135 
It's now possible to attach multiple time slots to a store. It's still necessary to set a default time slot for retro-compatibility. 
---
When multiple slots are configured, it's possible to switch in the delivery form.
=> Multiple time slots for stores

src/Controller/EmbedController.php
There's a missing param when we try to render summary screen after a failed payment for a form delivery.
=> Add missing param to summary screen

app/DoctrineMigrations/Version20220307181621.php, features/fixtures/ORM/optin_consents.yml, features/optins.feature, js/app/i18n/locales/en.json, js/app/i18n/locales/es.json, js/app/optins/AskForOptinsModal.js, js/app/optins/index.js, src/Action/MyOptinConsents.php, src/Action/UpdateOptinConsent.php, src/Controller/AdminController.php, src/Entity/OptinConsent.php, src/EventListener/RegistrationListener.php, src/Resources/config/doctrine/OptinConsent.orm.xml, templates/index/index.html.twig, webpack.config.js
With this PR now we are able to ask for optin consents to existing users:
https://user-images.githubusercontent.com/4819244/157557840-2ae862a8-9e39-495f-9ea6-3bd2ad69233b.mp4
=> Ask consent to existing users

features/tasks.feature, js/app/dashboard/components/TaskGroup.js, js/app/dashboard/components/UnassignedTasks.js, js/app/dashboard/dashboard.scss, js/app/dashboard/redux/actions.js, src/Entity/Task/Group.php
This PR adds the possbility to change the name of a group (https://github.com/coopcycle/coopcycle-web/issues/3223)
User can change the name after clicking in the new 'pencil' icon. 
When that icon is pressed, an editable input will be shown where pressing Enter or clicking 'check' icon will submit the action or pressing Escape or clicking 'close' icon will cancel the operation and replace the input with the original group name.
How it works:
https://user-images.githubusercontent.com/4819244/166987819-154fbff4-55d9-4d90-a554-a04c633ca34e.mp4
=> Possibility to change the name of a group

phpstan.neon, src/Form/Type/AsapChoiceLoader.php, src/Service/TimeRegistry.php, src/Utils/OrderTimeHelper.php, tests/AppBundle/Form/Type/AsapChoiceLoaderTest.php, tests/AppBundle/Utils/OrderTimeHelperTest.php
Fixes #3009
As a result, (with a average preparation + shipping of 20 minutes in the example below) for a shop that closes at 6:30PM, the last slot ends at 6:50PM
---
=> Append average preparation + shipping time to last time slot

features/dispatch.feature, features/tasks.feature, js/app/dashboard/components/ContextMenu.js, js/app/dashboard/redux/actions.js, js/app/dashboard/redux/taskEntityReducers.js, src/Entity/Task/Group.php
Closes #3251 
Now new groups are visible.
Rendering of TaskGroup wasn't working because after creating a group we weren't sending its ID and we use it as the key to loop all the groups.
https://user-images.githubusercontent.com/4819244/171052049-1ca21820-6876-44d4-bc70-7e900575a30c.mp4
=> Fix task groups

features/fixtures/ORM/restaurants.yml, features/restaurants.feature, src/Entity/LocalBusiness.php, src/Serializer/RestaurantNormalizer.php
Fist step for #3188, this adds a `facets` property to every restaurant entry, so that search filters can be implemented client-side. To ease client-side usage, it returns translated values out of the box.
=> Return facets property in restaurant list API response

src/Doctrine/EventSubscriber/TaskRecurrenceRuleSubscriber.php, src/Doctrine/EventSubscriber/TaskSubscriber.php, src/Entity/Address.php, src/Service/Geocoder.php, tests/AppBundle/Doctrine/EventSubscriber/TaskSubscriberTest.php
=> Editing issues when recurrent task and task address edit

js/app/forms/delivery.js, js/app/widgets/DateRangePicker.js, js/app/widgets/DateTimePicker.js, src/Form/DeliveryType.php, templates/delivery/form.html.twig
Closes #3465 
**Store with timeslot configured. Admin user is able to select a free range**
**Store with timeslot configured. Store user is only able to select a timeslot, not a free range**
**Store without a timeslot configured. Admin user is able to select a free range**
**Store without a timeslot configured. Store user is able to select a range only in the future**
=> Allow admins to select a date in the past when creating a delivery

app/config/config.yml, app/config/services.yml, features/search.feature, src/Action/Search/ShopsProducts.php, src/Doctrine/EventSubscriber/ShopsEventsForTypesenseSubscriber.php
This is done in three steps:
- Add a new `enabled` field to products search index
- Disable/enable products in the search index based on restaurants enabled status. Done in a postUpdate listener *manually* using TypesenseClient.
- Filter products by enabled status.
=> fix: search returning disabled restaurants products

src/EventListener/Upload/UploadListener.php
Fixes import problem reported as not having UTF8 encoding, turns out some of our Windows PC on México generate CSV files with  Windows1252 encoding. I validate the encoding and convert those files to UTF8.
=> Csv encoding

features/dispatch.feature, features/fixtures/ORM/tasks.yml, features/tasks.feature, src/Action/Task/AddImagesToTasks.php, src/Action/Task/Assign.php, src/Action/Task/AssignTrait.php, src/Action/Task/BulkAssign.php, src/Action/Task/BulkMarkAsDone.php, src/Action/Task/Done.php, src/Action/Task/DoneTrait.php, src/Entity/Task.php, src/Serializer/TaskImageNormalizer.php
New API endpoints that allow:
- Assign multiple tasks to a courier at once
- Mark multiple tasks as done at once
- Assign images (photos or signatures) to multiple tasks
Related to https://github.com/coopcycle/coopcycle-app/issues/1476.
A courier can select multiple tasks to complete and attach same images/signatures to all of them. In admin panel you can see the same images for all the tasks:
https://user-images.githubusercontent.com/4819244/224723657-ba4ca709-70fa-40b2-b262-2958114e844a.mp4
=> Bulk api operations for tasks

bin/demo, src/Controller/AdminController.php, src/Form/EmbedSettingsType.php, templates/admin/forms.html.twig, translations/messages.en.yml, translations/messages.es.yml
Creación de nuevo campo 'ShowOnHomePage' en DeliveryForm para configurar si un formulario se muestra o no en la página principal. Con validación para que sólo un formulario esté activo a la vez
=> Creación de nuevo campo 'ShowOnHomePage' en DeliveryForm

cube/TasksExportUnified.js, src/Form/TaskExportType.php
Some tasks have more than one `task_collection_item` associated. 
Now we are avoiding duplication of tasks sorting by `task.id` and `task_collection_item.position` and then for each task duplicated we keep the first one (the one with minimum position value in the collection).
=> Avoid duplicated tasks in export

app/config/services.yml, src/EventListener/Upload/UploadListener.php, src/MessageHandler/ImportTasksHandler.php, src/Spreadsheet/TaskSpreadsheetParser.php
Closes #3445 
https://github.com/coopcycle/coopcycle-web/assets/4819244/5f026152-db00-40a4-bc17-0e4c1c9ffd0a
- Tasks with group name in csv file are grouped under that name after the import.
- Tasks without a group name in csv file are grouped under a default group (Import d/m h:s) as was the case before this implementation.
https://github.com/coopcycle/coopcycle-web/assets/4819244/066f3891-68d2-41be-874c-e31ab7229084
- Tasks with a group name equal to an already used one are imported and grouped in a new group but with the same name as the existing one (users should avoid this case).
=> New group column in tasks import

src/Service/StripeManager.php, tests/AppBundle/Service/StripeManagerTest.php
When user wants to pay with a saved credit card we have to send the customer id with the payment intent even if restaurant is connected but doesn't pay stripe fees.
=> Send customer to stripe

src/Controller/AdminController.php, templates/admin/deliveries.html.twig
Closes #3622 
In /admin/deliveries now we have 3 tabs: Today, Upcoming and Past. All of them support pagination.
https://github.com/coopcycle/coopcycle-web/assets/4819244/6efacdd5-392d-48dd-a1f1-413858da42ac
=> Implement tabs and pagination for deliveries screen

src/Controller/AdminController.php, src/Controller/Utils/StoreTrait.php, src/Exception/DateTimeParseException.php, src/Form/DeliveryImportType.php, src/Spreadsheet/AbstractSpreadsheetParser.php, src/Spreadsheet/DeliverySpreadsheetParser.php, src/Spreadsheet/SpreadsheetParseResult.php, templates/admin/deliveries.html.twig, tests/AppBundle/Spreadsheet/DeliverySpreadsheetParserTest.php, translations/messages.en.yml, translations/messages.es.yml
Closes #1726 
In order to make the error massages even more helpful when import deliveries: 
https://github.com/coopcycle/coopcycle-web/assets/4819244/ed0fe9b3-afa9-4fe2-b519-cfa5e2eceab8
**Explanation of new messages after imports**
=> Improve errors messages for delivery import

features/dispatch.feature, features/fixtures/ORM/tours.yml, features/tasks.feature, js/app/dashboard/components/RightPanel.js, js/app/dashboard/components/Task.js, js/app/dashboard/components/TaskGroup.js, js/app/dashboard/components/TaskList.js, js/app/dashboard/components/Tour.js, js/app/dashboard/components/UnassignedTasks.js, js/app/dashboard/components/UnassignedTour.js, js/app/dashboard/components/UnassignedTours.js, js/app/dashboard/redux/actions.js, js/app/dashboard/redux/selectors.js, js/app/dashboard/redux/taskEntityReducers.js, js/app/i18n/locales/en.json, js/shared/src/logistics/redux/actions.js, js/shared/src/logistics/redux/uiReducers.js, src/Api/DataTransformer/TourInputDataTransformer.php, src/Entity/Tour.php, src/Serializer/TaskNormalizer.php
Fixes #3597
Fixes #3552
See #3595
=> 3597 allow reordering tasks of a tour

.eslintrc.js, js/app/i18n/locales/en.json, js/app/i18n/locales/es.json, js/app/payment/mercadopago.js, js/app/widgets/StripePaymentForm.js, package-lock.json, package.json, src/Service/MercadopagoManager.php, templates/embed/delivery/summary.html.twig, templates/order/payment.html.twig, templates/public/order.html.twig
Fixes #3701 
https://github.com/coopcycle/coopcycle-web/assets/4819244/28f6f22e-6872-41bd-ae84-2135e164abeb
=> Migration to MercacdoPago SDK V2 and implementation of Bricks

src/Entity/Delivery.php, src/Entity/Task.php, src/ExpressionLanguage/PickupExpressionLanguageProvider.php, src/Pricing/PricingRuleMatcherInterface.php, src/Service/DeliveryManager.php, tests/AppBundle/Service/DeliveryManagerTest.php
Fixes #3047
This is the simplest implementation possible, without modifying the pricing editor. 
When using the "All the matching rules" method of calculation AND having multiple tasks, the system will iterate over all the tasks, and try to apply the rules. 
⚠️ There are still some limitations. 
- Some conditions don't make sense at the task level, for example the distance. 
- Also, timing conditions won't work as expected when using "less than" operator. It is because when using the "Difference (hours)" condition, it translates to an expression like `diff_hours(pickup) < 3`. The current implementation returns `-1` when the task is not of the expected type (i.e, when evaluating a dropoff), so it will still match the "less than" operator. A solution would be to change the generated …
=> Apply pricing rules for deliveries with multiple tasks.

app/config/config.yml, assets/app.js, assets/bootstrap.js, assets/controllers.json, assets/styles/app.css, composer.json, composer.lock, js/app/i18n/locales/en.json, js/app/i18n/locales/es.json, js/app/notifications/NotificationList.js, js/app/notifications/index.js, package-lock.json, package.json, src/Controller/ProfileController.php, src/Service/TopBarNotifications.php, templates/profile/notifications.html.twig, translations/messages.en.yml, translations/messages.es.yml, webpack.config.js
Fixes #3655 and part of #3653 
This improvement uses "Symfony UX Turbo" a library with a lot of UX features and in this case we are using it to implement an infinite scroll in the notifications screen. 
Links of interest:
https://symfony.com/bundles/ux-turbo/current/index.html
https://turbo.hotwired.dev/handbook/frames
https://symfonycasts.com/screencast/symfony-doctrine/forever-scroll
Now the notifications are not automatically removed when user open the modal. Now notifications can only be removed after clicking the "remove" icon on each notification or selecting multiple notifications in the notification screen.
Here a video to see how work now the notification modal and the screen:
https://github.com/coopcycle/coopcycle-web/assets/4819244/75ec1032-e37f-4d50-ae3b-252c16723cf9
=> Notifications improvements

js/app/foodtech/dashboard/redux/actions.js, js/app/foodtech/dashboard/redux/middlewares.js, js/app/foodtech/dashboard/redux/reducers.js, js/app/i18n/locales/en.json, js/app/i18n/locales/es.json, js/app/i18n/locales/fr.json
Closes #3081 
When an order is delayed a new notification will be shown notifying to restaurant when the dispatcher delays an order and vice versa if restaurant delays an order. This notification will be visible only if the user is or has a tab open in the orders dashboard (admin or restaurant).
https://github.com/coopcycle/coopcycle-web/assets/4819244/5f6fb2c3-6cf7-4c10-bfa6-def3fa960f4c
=> Notify restaurante/dispatcher when an order is delayed

js/app/i18n/locales/en.json, js/app/i18n/locales/es.json, js/app/notifications/NotificationList.js, js/app/notifications/index.js, src/Controller/ProfileController.php, src/Service/TopBarNotifications.php, templates/profile/notifications.html.twig
Closes #3773 
https://github.com/coopcycle/coopcycle-web/assets/4819244/948ba11c-ce84-466f-85cd-ed913465f650
=> New action to delete all notifications at once

app/config/services/twig.yml, app/config/services/validators.yml, features/settings.feature, src/Action/Settings.php, src/Service/SettingsManager.php, src/Twig/CoopCycleExtension.php, src/Twig/SettingResolver.php, src/Utils/Settings.php, src/Validator/Constraints/GoogleApiKey.php, src/Validator/Constraints/GoogleApiKeyValidator.php, templates/admin.html.twig, translations/messages.en.yml, translations/messages.fr.yml, translations/validators.en.yml, translations/validators.fr.yml
We will now periodically (every 24h) send a request to Google Maps API, to make sure the API Key is still valid. 
Fixes #3910 
Also removes deprecated code for Algolia
=> Validate Google Maps API Key

app/DoctrineMigrations/Version20240103181510.php, app/config/services/forms.yml, js/app/product/form.js, src/Entity/BusinessRestaurantGroupPriceWithTax.php, src/Entity/Sylius/ProductVariant.php, src/Form/BusinessRestaurantGroupPriceType.php, src/Form/ProductType.php, src/Form/Type/PriceWithTaxType.php, src/Resources/config/doctrine/Sylius.ProductVariant.orm.xml, src/Sylius/Product/LazyProductVariantResolver.php, src/Sylius/Product/LazyProductVariantResolverInterface.php, templates/form/product.html.twig, templates/restaurant/product.html.twig, translations/messages.en.yml, translations/messages.es.yml
As mentioned [in this issue](https://github.com/coopcycle/coopcycle-web/issues/3877) we need a way to define different prices for a `BusinessAccount` (or Platform catering). 
With this PR users are able to define an extra price for each existing `BusinessRestaurantGroup` (similar entity as Hubs).
https://github.com/coopcycle/coopcycle-web/assets/4819244/02f23295-5007-44da-a455-d58ff7459d53
=> Product pricing option for business restaurant group

src/Form/SettingsType.php, src/Utils/Settings.php, templates/admin/settings.html.twig, translations/messages.en.yml, translations/messages.fr.yml
Now coop admins are asked to fill `company_legal_name` and `company_legal_id` in their settings.
=> Add legal fields in settings

src/Entity/Sylius/Order.php, src/Service/RouteOptimizer.php, src/Sylius/Order/OrderInterface.php, src/Utils/ShippingTimeCalculator.php, tests/AppBundle/Service/RouteOptimizerTest.php, tests/AppBundle/Utils/ShippingTimeCalculatorTest.php
Currently, to calculate the shipping time, we calculate the travel time by bike between the pickup address and the dropoff address. 
In the context of business accounts, the pickup address is kind of "random", because it is resolved from the first restaurant of the group
https://github.com/coopcycle/coopcycle-web/blob/d2c6c354408a611cf4d1ed23e0a48701a9196443/src/Entity/BusinessRestaurantGroup.php#L65-L75
This pull request makes a better calculation of the shipping time in this context, and also in the context of multiple pickups in the future: the travel time is calculated using pickup addresses sorted from the farest to the closest, with a final dropoff.
=> Implement shipping time calculation for multiple pickups

js/app/restaurant/item.scss, templates/restaurant/index.html.twig
Fixes:
✅ opening hours might not fit into the modal, for example: https://demo.coopcycle.org/fr/restaurant/33-la-cabane-du-sud
✅ menu: white margin on the bottom of the page
✅ placeholder banners are not displayed on the restaurant page
=> menu redesign fixes

js/app/dashboard/components/context-menus/TasksContextMenu.js, js/app/dashboard/redux/__tests__/utils.test.js, js/app/dashboard/redux/actions.js, js/app/dashboard/redux/handleDrag.js, js/app/dashboard/redux/reducers.js, js/app/dashboard/redux/selectors.js, js/app/dashboard/redux/utils.js
Following fixes :
- filter out duplicate tasks in "unassigned tasks / unassigned tours" (bug with the options for sorting unassigned tasks) #4067
- move order tasks together on drag n drop (even for unassign) #4064  
- clear out task selection on create tour, modify tour, create group, modify group #4071
=> Tours fixes 1.1

features/fixtures/ORM/optimizer/set1.yml, features/fixtures/ORM/optimizer/set2.yml, src/Api/Filter/TaskFilter.php, src/Entity/TaskCollection.php, src/Entity/Tour.php, src/Service/RouteOptimizer.php, src/Vroom/Shipment.php, tests/AppBundle/Service/RouteOptimizerTest.php
issue #4007
this modifies the routing proplem class; so the tours are isolated for the algorithm
- we create a "shipment" object with start and end of the tour
- tasks that are in the tour are reinserted in order in between tour start and end
=> clean: keep tour as an untouched group when optimizing

js/app/components/AddressAutosuggest.js, js/app/delivery/AddressBook.js, js/app/delivery/AddressBook.scss, js/app/delivery/SavedAddressBox.js, js/app/forms/delivery.js, js/app/i18n/locales/en.json, js/app/i18n/locales/es.json, src/Form/AddressType.php, templates/form/address_book.html.twig
Closes #3825
This change allows to dispatchers and shop owners searching saved addresses by its name in the delivery form.
Note that Autosuggest component already show saved addresses but is limited only to 5 addresses. This new search component will search for all the saved address.
https://github.com/coopcycle/coopcycle-web/assets/4819244/9d70aa87-36d1-4ea1-bf9f-bf10ae834f4f
=> Allow search saved addresses in delivery form

src/Command/GeofencingCommand.php
=> fix: check if customer is null before sending geofencing message

src/Controller/AdminController.php, src/Controller/UserController.php, src/Entity/BusinessAccountInvitation.php, src/EventListener/AuthenticationWebSuccessHandler.php, src/Form/BusinessAccountType.php, src/Resources/config/routing/admin.yml, templates/_partials/profile/definition_password_for_business_account.html.twig, templates/_partials/profile/existing_user_ask_login_form.html.twig, templates/admin/business_account.html.twig, templates/emails/business_account_send_invitation.mjml.twig, translations/emails.en.yml, translations/emails.es.yml, translations/messages.en.yml, translations/messages.es.yml
With these changes now an existing user should be able to accept the invitation to configure their business account (https://github.com/coopcycle/coopcycle-web/issues/4217).
**Existing user clicks on invitation but is not logged in in the app**
Now we ask for login first, and then we skip the step 1 (personal account creation) and send the user to the 2nd step when should complete the info of the company.
https://github.com/coopcycle/coopcycle-web/assets/4819244/b3a1ada0-847c-4c25-99c7-868a0ff6eebb
**Existing user opens the invitation while is already logged in in the app **
After click in the invitation we skip the step 1 (personal account creation) and send the user to the 2nd step when should complete the info of the company.
https://github.com/coopcycle/coopcycle-web/assets/4819244/b6b …
=> Fix busines account for existing users

src/Controller/UserController.php, templates/_partials/profile/definition_password_for_business_account.html.twig, templates/_partials/profile/definition_password_for_classical_users.html.twig, templates/_partials/profile/existing_user_ask_login_form.html.twig, templates/_partials/profile/personal_information_form.html.twig, templates/profile/associate_loggedin_user_to_business_account.html.twig, translations/messages.en.yml, translations/messages.es.yml
With these changes now an existing user should be able to accept the invitation to associate its account to a Business Account (https://github.com/coopcycle/coopcycle-web/issues/4251).
**An existing user opens the link of the invitation while they are not logged in to the platform**
https://github.com/coopcycle/coopcycle-web/assets/4819244/c2ab6d5b-1a25-46d8-83c7-4329a83ba635
**An existing and logged in user opens the link of the invitation**
https://github.com/coopcycle/coopcycle-web/assets/4819244/fce861b8-9da6-41d4-8635-ed3e017bec37
=> Associate existing users as business accounts employees

app/config/config.yml, app/config/services.yml, src/Controller/UserController.php, src/Form/BusinessAccountRegistration.php, src/Form/BusinessAccountRegistrationFlow.php, src/Form/BusinessAccountRegistrationForm.php, src/Form/BusinessAccountType.php, src/Service/InvitationLinkProviderService.php, templates/_partials/profile/business_account_invitation_form.html.twig, templates/_partials/profile/definition_password_for_business_account.html.twig, templates/_partials/profile/invitation_link.html.twig, templates/bundles/NucleosProfileBundle/Registration/confirmed.html.twig, translations/messages.en.yml, translations/messages.es.yml
#4311  The idea is to not display the invitation link until the registration process has been completed. Now the Business Account registration flow has 2 steps instead of 3 and in the 'confirmed registration' screen now we are showing the invitation link section.
https://github.com/coopcycle/coopcycle-web/assets/4819244/73345850-17e8-4927-a72e-c69a9bb5614f
=> Invitation link moved to confirmed registration screen

src/Controller/ProfileController.php, templates/_partials/order/list.html.twig, templates/profile.html.twig, templates/profile/business_account_orders.html.twig, translations/messages.en.yml, translations/messages.es.yml
New screen where Business Account managers can see the orders made by users/employees on behalf of the company.
With this screen the menu section for Business Accounts has changed. Now it has a sub menu section to access to the configuration of Company information and another for the orders:
https://github.com/coopcycle/coopcycle-web/assets/4819244/5148efb0-3033-4bd4-a86f-48c2d8aeba7c
=> Orders screen for business account managers

app/DoctrineMigrations/Version20240617121101.php, js/app/components/RulePicker.js, js/app/delivery/pricing-rule-parser.js, src/Entity/Task.php, src/ExpressionLanguage/PickupExpressionLanguageProvider.php, tests/AppBundle/ExpressionLanguage/PickupExpressionLanguageProviderTest.php, tests/AppBundle/Service/DeliveryManagerTest.php
Fixes #3977
Since 0437ce115b9b970306e5a1343bf3de7c697af467, it's possible to define time-based functions in pricing rules, i.e: 
- `diff_days(pickup)`
- `diff_hours(pickup)`
- `time_range_length(pickup, 'hours')`
As those functions were first designed to work at **delivery** level (i.e 2 tasks, pickup & dropoff), to make them work at **task** level while not breaking everything, [we inject a fake/empty task in the expression language context](https://github.com/coopcycle/coopcycle-web/blob/b493c7a30ee43439e0e7231d6f6f9c641ac7ea96/src/Entity/Task.php#L1106-L1127), and we return `-1` when we encounter this fake/empty task, as a way to "skip" the rule matching. 
It [works well for distance evaluation](https://github.com/coopcycle/coopcycle-web/blob/b493c7a30ee43439e0e7231d6f6f9c641ac7ea96/src …
=> Support multi points in time based pricing functions 

js/app/restaurant/components/Order/index.js, js/app/restaurant/item.js
fixed: avoid calling sync() action twice on loading a restaurant page: http://*/en/restaurant/3-burger-bar
Which leads to a double POST`/*/restaurant/*/cart` requests with in turn leads to a creation of double adjustments (delivery fees)
❗️you will probably see double POST requests in the development environment, that due to the `StrictMode`
=> fixed: avoid calling `sync()` action twice

app/config/message_bus/task.yml, app/config/services.yml, js/app/dashboard/components/Task.js, js/app/dashboard/redux/middlewares.js, src/Doctrine/EventSubscriber/OrderSubscriber.php, src/Domain/Task/Command/Update.php, src/Domain/Task/Event/TaskUpdated.php, src/Domain/Task/Handler/UpdateHandler.php, src/Domain/Task/Reactor/NotifyUrbantz.php, src/Domain/Task/Reactor/TriggerWebhook.php, src/Entity/Delivery.php, src/Entity/TaskCollection.php, src/Service/ActivityManager.php, src/Service/TaskManager.php
I added the `TaskUpdated` event before I needed to update the task data in the dispatch when the order number was finally set (the task is added before on `TaskCreated` event)
=> In the dispatch panel, show <order_number>-<delivery_position> instead of task.id

app/config/services.yml, features/carts.feature, features/fixtures/ORM/payment_methods.yml, features/foodtech.feature, features/orders.feature, features/orders_adhoc.feature, src/Action/Order/ConfigurePayment.php, src/Action/Order/PaymentDetails.php, src/Action/Order/PaymentMethods.php, src/Api/DataTransformer/ConfigurePaymentInputDataTransformer.php, src/Api/DataTransformer/EdenredCredentialsInputDataTransformer.php, src/Api/Dto/ConfigurePaymentInput.php, src/Api/Dto/ConfigurePaymentOutput.php, src/Api/Dto/EdenredCredentialsInput.php, src/Api/Dto/PaymentDetailsOutput.php, src/Controller/EdenredController.php, src/Edenred/Client.php, src/Entity/Sylius/Order.php, src/Resources/config/serialization.yml, src/Serializer/JsonLd/OrderNormalizer.php
This pull requests adds 2 new endpoints: 
- `PUT /orders/{id}/edenred_credentials` to update the Edenred credentials of the customer of an order
- `PUT /orders/{id}/payment` to configure the payment method of an order, i.e for Edenred it will calculate the amount breakdown (customers can spend a maximum of 25€ per day with Edenred). 
It also adds a proxy to obtain an access token from Edenred without exposing the client secret.
=> Get ready for Edenred implementation on the app

app/DoctrineMigrations/Version20241009072602.php, app/config/message_bus/task.yml, app/config/services.yml, features/tasks.feature, src/Action/Incident/CreateIncident.php, src/Action/Task/FailureReasons.php, src/Domain/Task/Command/Incident.php, src/Domain/Task/Event/TaskIncidentReported.php, src/Domain/Task/Handler/IncidentHandler.php, src/Domain/Task/Reactor/NotifyLoopeat.php, src/Entity/Incident/Incident.php, src/Entity/Sylius/Order.php, src/Incident/FailureReasonsResolverInterface.php, src/Incident/LoopeatFailureReasonsResolver.php, src/LoopEat/Client.php, src/Resources/config/doctrine/Incident.Incident.orm.xml, src/Service/TaskManager.php, translations/messages.en.yml
This pull request introduces a way to add dynamic failure reasons (via classes implementing `FailureReasonsResolverInterface`). 
Also, it uses the `metadata` property of a `FailureReason` to describe additional form fields that should be attached to an incident. In this case, the form fields will allow describing how many zero waste containers have been returned by the customer. 
Finally, it adds a `metadata` property to the `Incident` class, to allow storing the form data.
=> Allow reporting zero waste incidents

src/Form/Checkout/CheckoutCustomerType.php
Bug report: https://coopcycle.slack.com/archives/C4UT4DGQ3/p1731192393132159
Currently we re-use previously entered data:
https://github.com/coopcycle/coopcycle-web/blob/dc62049791d2754e2d123ead470c6bdf460f495c/src/Form/Checkout/CheckoutCustomerType.php#L98-L101
But we should update it with the most recently entered phone number as we already do for the mobile app/API:
https://github.com/coopcycle/coopcycle-web/blob/dc62049791d2754e2d123ead470c6bdf460f495c/src/Action/Order/Assign.php#L76-L92
=> use the most recent phone number for a returning customer (guest checkout)

src/Action/Task/Assign.php, src/Action/Task/AssignTrait.php, src/Action/Task/BulkAssign.php, src/Controller/BarcodeController.php
The action_token enables temporary elevated permissions for couriers.
It allows specific actions (like self-assignment) on the scanned task only.
Generation:
- Uses BarcodeUtils::getToken/1 to get the label's token
- Hashes it with xxh3 algorithm for additional security
- Uses runtime secret key to prevent token guessing
Security:
- Scoped to single task (token invalid for other tasks)
- Cannot be forged without access to runtime secret
=> Add security token that allow a rider to use assign/unassign

templates/_partials/delivery/list.html.twig, templates/_partials/delivery/summary.html.twig, templates/_partials/order/customer.html.twig, templates/_partials/order/list.html.twig, templates/_partials/order/summary.html.twig
- add an "owner" column as for delivery (store or restaurant)
- add a summary for lastmile orders
- move customer information/link to summary column
After
Before
=> Improve order table display for lastmile/local commerce

features/deliveries.feature, features/deliveries_multi.feature, features/dispatch.feature, features/tasks.feature, src/Action/Task/Collection.php, src/Serializer/TaskNormalizer.php, src/Utils/Barcode/BarcodeUtils.php
Fixes #4818
It's slightly better than having them at task level, but still, we only have an array of labels, and we don't know which label corresponds to which package when quantity is > 1.
=> Serialize labels as part of task packages

features/woopit.feature, src/Action/Woopit/CreateDeliveryTrait.php, src/Action/Woopit/DeliveryRequest.php, src/Action/Woopit/PackagesTrait.php, src/Action/Woopit/QuoteRequest.php, src/Entity/Woopit/QuoteRequest.php
=> Implement properly parcels & labels in Woopit delivery request.

src/Entity/Store.php
Related PR: https://github.com/coopcycle/coopcycle-app/pull/1949
We need to allow a dispatcher to call the endpoint to list all the stores.
=> [PERTE-197] Allowing 'ROLE_DISPATCHER' to call 'GET /api/stores' endpoint

cypress/fixtures/dispatch.yml, features/retail_prices.feature, src/Api/DataTransformer/DeliveryInputDataTransformer.php, src/Api/Resource/RetailPrice.php, src/Entity/Store.php, src/Security/StoreVoter.php
Related PRs:
* https://github.com/coopcycle/coopcycle-app/pull/1949
* https://github.com/coopcycle/coopcycle-web/pull/4906
We need to allow a dispatcher to call this endpoints:
- api/stores/{id}/time_slots
- api/stores/{id}/packages
- api/retail_prices/calculate
Also, added fixture for test Dispatch->Create delivery in app mobile
=> [PERTE-197] Allowing 'ROLE_DISPATCHER' to call endpoints

cypress/e2e/invoicing/export_data_for_invoicing.cy.js, cypress/e2e/local-commerce/@admin/recurrence_rules/create_delivery_with_recurrence_rule_as_admin.cy.js, features/fixtures/ORM/stores.yml, features/stores.feature, src/Api/EventSubscriber/SoftDeletedSubscriber.php, src/Controller/Utils/StoreTrait.php
=> [PERTE-275] Do not list/display deleted stores by default for `/api/stores` endpoint

src/Utils/MenuEditor.php
The bug : the "products" column in the menu editor form is empty
Why? I am not PHP wizard but when we added the annotation with rector, the value of "products" in the twig template is now NULL (here https://github.com/coopcycle/coopcycle-web/commit/534bc0a395bbc31f60ae857446f6cc828f6756c5#diff-cb098e0335fc596eab9af092879d3298620efb6a6ae84441078dd5976738ca8eR12 )
=> Fix: "products" column (products outside a section) is empty in menu sections form

config/packages/twig.yaml, config/services.yaml, src/Entity/Sylius/LoopeatOrderDetails.php, src/Entity/Sylius/Order.php, src/LoopEat/ContextInitializer.php, src/Sylius/OrderProcessing/OrderDepositRefundProcessor.php, src/Twig/CoopCycleExtension.php, src/Twig/LoopeatRuntime.php, templates/emails/order/accepted.mjml.twig, tests/AppBundle/Sylius/OrderProcessing/OrderDepositRefundProcessorTest.php
The `LOOPEAT_PROCESSING_FEE` env var can now contain an expression. If it contains a number, it will still work like before. 
Fixes #4971
=> Calculate dynamically zero waste processing fee

cypress/e2e/invoicing/export_data_for_invoicing.cy.js, cypress/e2e/invoicing/export_data_for_invoicing_odoo.cy.js, js/app/admin/invoicing/components/ExportModalContent.js, js/app/admin/invoicing/components/OrdersTable/index.js, js/app/admin/invoicing/components/OrdersToInvoice/index.js, js/app/admin/invoicing/components/OrganizationsTable/index.js, src/Api/Dto/InvoiceLineItem.php, src/Api/State/InvoiceLineItemsProvider.php
Fixed:
- clicking one shop or expanding one shop clicks or expands all of them
- the orders could be duplicated within an unfolded organisation (due to pagination issues)
- export file is empty
=> Fix: invoicing page

cypress/e2e/package-delivery/import/deliveries.cy.js, cypress/e2e/pricing/setup_simple_km_based_pricing_rule.cy.js, cypress/e2e/pricing/setup_simple_matrix_pricing_rule.cy.js, cypress/e2e/pricing/setup_simple_multi_point_pricing_rule.cy.js, cypress/e2e/pricing/setup_time_slot_based_pricing_rule.cy.js, fixtures/ORM/packages.yml, fixtures/ORM/time_slots_pagination.yml, js/app/api/slice.js, js/app/api/utils.js, js/app/components/delivery-form/DeliveryForm.js, js/app/components/delivery-form/Task.js, js/app/delivery/pricing/components/RulePickerLine/TimeSlotPicker.js, src/MessageHandler/Order/UpdateState.php, templates/_partials/order/list.html.twig, tests/AppBundle/Domain/Order/Reactor/UpdateStateTest.php
Fixes: https://github.com/coopcycle/coopcycle/issues/386
The order does not appear in the order list, because the order state is not updated, and the orders stays in the state `Cart`
Why?
We process `ImportDeliveries` message asynchronously and flush database changes at the end of the import: https://github.com/coopcycle/coopcycle-web/blob/master/src/MessageHandler/ImportDeliveriesHandler.php#L125
However, `OrderCreated` event is dispatched after the `ImportDeliveries` message is handled: https://github.com/coopcycle/coopcycle-web/blob/master/src/MessageHandler/Order/Command/OnDemandHandler.php#L30-L32 That's why, as I understand, all changes `UpdateState` makes are not written to the database.
(As I understand, in other situations `OrderCreated` and similar events are dispatched during …
=> Fix: When a client imports a file, the tasks appeared correctly in the dashboard but are not available in the order list

Makefile, src/Doctrine/EventSubscriber/TaskListSubscriber.php, tests/AppBundle/MessageHandler/Delivery/DeliveryCreatedHandlerTest.php
Main changes were done at coopcycle-app's PR:
https://github.com/coopcycle/coopcycle-app/pull/2042
The solution was to not consider as `"selectNotificationsToDisplay"` directly in app, because we still need the notification to update the task/tasklist in the app for every subscribed user (centrifugo / websocket).
=> [PERTE-451] Avoid task updated notification modal for admins and dispatchers
